CREATE TABLE trainers
(
	id		SERIAL		PRIMARY KEY,
	username	VARCHAR(12)	NOT NULL	UNIQUE,
	password	VARCHAR(20)	NOT NULL,
	email		VARCHAR(256)			UNIQUE,
	created		TIMESTAMP	NOT NULL
);

CREATE TABLE teams
(
	id		SERIAL	PRIMARY KEY,
	id_trainer	SERIAL	NOT NULL	REFERENCES trainers	ON DELETE CASCADE ON UPDATE CASCADE,
	id_regulation	SERIAL	NOT NULL	REFERENCES regulations	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE tournaments
(
	id		SERIAL		PRIMARY KEY,
	name		VARCHAR(25)	NOT NULL	UNIQUE,
	id_regulation	SERIAL		NOT NULL	REFERENCES regulations	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE trainers_tournaments
(
	id_trainer	INT	REFERENCES trainers	ON DELETE CASCADE ON UPDATE CASCADE,
	id_tournament	INT	REFERENCES tournaments	ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY(id_trainer, id_tournament)
);

CREATE TABLE regulations
(
	id		SERIAL		PRIMARY KEY
	name		VARCHAR(20)	NOT NULL,
	generation	SMALLINT	NOT NULL,
	year		SMALLINT	NOT NULL,
	rules		JSON		NOT NULL
);

CREATE TABLE  matches
(
	id_tournament	INT		REFERENCES tournaments	ON DELETE CASCADE ON UPDATE CASCADE,
	id_trainer_1	INT		REFERENCES trainers	ON DELETE CASCADE ON UPDATE CASCADE,
	id_trainer_2	INT		REFERENCES trainers	ON DELETE CASCADE ON UPDATE CASCADE,
	winner		SMALLINT	DEFAULT 0 CHECK (winner in (0, 1, 2)),
	CHECK (id_trainer_1 != id_trainer_2),
	PRIMARY KEY(id_tournament, id_trainer_1, id_trainer_2)
);

CREATE TABLE pokemon
(
	id			SERIAL		PRIMARY KEY,
	name			VARCHAR(20)	NOT NULL,
	base_stats		JSON		NOT NULL,	
	id_type_1		SMALLINT	NOT NULL	REFERENCES types ON DELETE CASCADE ON UPDATE CASCADE,
	id_type_2		SMALLINT			REFERENCES types ON DELETE CASCADE ON UPDATE CASCADE,
	id_ability_1		INT		NOT NULL	REFERENCES abilities ON DELETE CASCADE ON UPDATE CASCADE,
	id_ability_2		INT				REFERENCES abilities ON DELETE CASCADE ON UPDATE CASCADE,
	id_hidden_ability	INT				REFERENCES abilities ON DELETE CASCADE ON UPDATE CASCADE,
	generation		SMALLINT
);

CREATE TABLE movements
(
	id			SERIAL		PRIMARY KEY,
	name			VARCHAR(20)	NOT NULL,
	description		TEXT		NOT NULL,
	power			SMALLINT,
	precision		SMALLINT,
	id_type			SMALLINT	NOT NULL	REFERENCES types ON DELETE CASCADE ON UPDATE CASCADE,
	category		INT		NOT NULL,
	generation		SMALLINT	NOT NULL,
	unavailable_from	SMALLINT
);

CREATE TABLE pokemon_movements
(
	id_pokemon	INT	REFERENCES pokemon	ON DELETE CASCADE ON UPDATE CASCADE,
	id_movement	INT	REFERENCES movements	ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY(id_pokemon, id_movement)
);

CREATE TABLE abilities
(
	id		SERIAL		PRIMARY KEY,
	name		VARCHAR(20)	NOT NULL,
	description	TEXT		NOT NULL,
	generation	SMALLINT	NOT NULL
);

CREATE TABLE natures
(
	id		SERIAL		PRIMARY KEY,
	name		VARCHAR(15)	NOT NULL,
	stat_up		VARCHAR(3)	NOT NULL,
	stat_down	VARCHAR(3)	NOT NULL
);

CREATE TABLE items
(
	id			SERIAL		PRIMARY KEY,
	name			VARCHAR(20)	NOT NULL,
	description		TEXT		NOT NULL,
	generation		SMALLINT	NOT NULL,
	unavailable_from	SMALLINT
);

CREATE TABLE types
(
	id		SERIAL		PRIMARY KEY,
	name		VARCHAR(10)	NOT NULL,
	generation	SMALLINT	NOT NULL
);

CREATE TABLE selected_pokemon
(
	id		SERIAL		PRIMARY KEY,
	id_pokemon	INT		NOT NULL	REFERENCES pokemon	ON DELETE CASCADE ON UPDATE CASCADE,
	id_team		INT 		NOT NULL	REFERENCES teams	ON DELETE CASCADE ON UPDATE CASCADE,
	ability		SMALLINT	NOT NULL	CHECK (ability in (0, 1, 2)),
	id_nature	INT 		NOT NULL	REFERENCES natures	ON DELETE CASCADE ON UPDATE CASCADE,
	id_item		INT		NOT NULL	REFERENCES objects	ON DELETE CASCADE ON UPDATE CASCADE,
	moveset		JSON		NOT NULL,
	IVs		JSON		NOT NULL,
	EVs		JSON		NOT NULL,
	shiny		BOOLEAN		DEFAULT FALSE,
	nickname	VARCHAR(20)
);

