INSERT INTO items (name, description, generation) VALUES
(
	("Ability Shield", "Holder's Ability cannot be changed by any effect.", 9),
	("Abomasite", "If held by an Abomasnow, this item allows it to Mega Evolve in battle.", 6),
	("Absolite", "If held by an Absol, this item allows it to Mega Evolve in battle.", 6),
	("Absorb Bulb", "Raises holder's Sp. Atk by 1 stage if hit by a Water-type attack. Single use.", 5),
	("Adamant Crystal", "If held by a Dialga, its Steel- and Dragon-type attacks have 1.2x power.", 8),
	("Adamant Orb", "If held by a Dialga, its Steel- and Dragon-type attacks have 1.2x power.", 4),
	("Adrenaline Orb", "Raises holder's Speed by 1 stage if it gets affected by Intimidate. Single use.", 7),
	("Aerodactylite", "If held by an Aerodactyl, this item allows it to Mega Evolve in battle.", 6),
	("Aggronite", "If held by an Aggron, this item allows it to Mega Evolve in battle.", 6),
	("Aguav Berry", "Restores 1/3 max HP at 1/4 max HP or less; confuses if -SpD Nature. Single use.", 3),
	("Air Balloon", "Holder is immune to Ground-type attacks. Pops when holder is hit.", 5),
	("Alakazite", "If held by an Alakazam, this item allows it to Mega Evolve in battle.", 6),
	("Aloraichium Z", "If held by an Alolan Raichu with Thunderbolt, it can use Stoked Sparksurfer.", 7),
	("Altarianite", "If held by an Altaria, this item allows it to Mega Evolve in battle.", 6),
	("Ampharosite", "If held by an Ampharos, this item allows it to Mega Evolve in battle.", 6),
	("Apicot Berry", "Raises holder's Sp. Def by 1 stage when at 1/4 max HP or less. Single use.", 3),
	("Armor Fossil", "Can be revived into Shieldon.", 4),
	("Aspear Berry", "Holder is cured if it is frozen. Single use.", 3),
	("Assault Vest", "Holder's Sp. Def is 1.5x, but it can only select damaging moves.", 6),
	("Audinite", "If held by an Audino, this item allows it to Mega Evolve in battle.", 6),
	("Auspicious Armor", "Evolves Charcadet into Armarouge when used.", 9),
	("Babiri Berry", "Halves damage taken from a supereffective Steel-type attack. Single use.", 4),
	("Banettite", "If held by a Banette, this item allows it to Mega Evolve in battle.", 6),
	("Beast Ball", "A special Poke Ball designed to catch Ultra Beasts.", 7),
	("Beedrillite", "If held by a Beedrill, this item allows it to Mega Evolve in battle.", 6),
	("Belue Berry", "Cannot be eaten by the holder. No effect when eaten with Bug Bite or Pluck.", 3),
	("Berry Juice", "Restores 20 HP when at 1/2 max HP or less. Single use.", 2),
	("Berry Sweet", "Evolves Milcery into Alcremie when held and spun around.", 8),
	("Big Nugget", "A big nugget of pure gold that gives off a lustrous gleam.", 5),
	("Big Root", "Holder gains 1.3x HP from draining/Aqua Ring/Ingrain/Leech Seed/Strength Sap.", 4),
	("Binding Band", "Holder's partial-trapping moves deal 1/6 max HP per turn instead of 1/8.", 5),
	("Black Belt", "Holder's Fighting-type attacks have 1.2x power.", 2),
	("Black Glasses", "Holder's Dark-type attacks have 1.2x power.", 2),
	("Black Sludge", "Each turn, if holder is a Poison type, restores 1/16 max HP; loses 1/8 if not.", 4),
	("Blastoisinite", "If held by a Blastoise, this item allows it to Mega Evolve in battle.", 6),
	("Blazikenite", "If held by a Blaziken, this item allows it to Mega Evolve in battle.", 6),
	("Blue Orb", "If held by a Kyogre, this item triggers its Primal Reversion in battle.", 6),
	("Bluk Berry", "Cannot be eaten by the holder. No effect when eaten with Bug Bite or Pluck.", 3),
	("Blunder Policy", "If the holder misses due to accuracy, its Speed is raised by 2 stages. Single use.", 8),
	("Booster Energy", "Activates the Protosynthesis or Quark Drive Abilities. Single use.", 9),
	("Bottle Cap", "Used for Hyper Training. One of a Pokemon's stats is calculated with an IV of 31.", 7),
	("Bright Powder", "The accuracy of attacks against the holder is 0.9x.", 2),
	("Bug Gem", "Holder's first successful Bug-type attack will have 1.3x power. Single use.", 5),
	("Bug Memory", "Holder's Multi-Attack is Bug type.", 7),
	("Buginium Z", "If holder has a Bug move, this item allows it to use a Bug Z-Move.", 7),
	("Burn Drive", "Holder's Techno Blast is Fire type.", 5),
	("Cameruptite", "If held by a Camerupt, this item allows it to Mega Evolve in battle.", 6),
	("Cell Battery", "Raises holder's Attack by 1 if hit by an Electric-type attack. Single use.", 5),
	("Charcoal", "Holder's Fire-type attacks have 1.2x power.", 2),
	("Charizardite X", "If held by a Charizard, this item allows it to Mega Evolve in battle.", 6),
	("Charizardite Y", "If held by a Charizard, this item allows it to Mega Evolve in battle.", 6),
	("Charti Berry", "Halves damage taken from a supereffective Rock-type attack. Single use.", 4),
	("Cheri Berry", "Holder cures itself if it is paralyzed. Single use.", 3),
	("Cherish Ball", "A rare Poke Ball that has been crafted to commemorate an occasion.", 4),
	("Chesto Berry", "Holder wakes up if it is asleep. Single use.", 3),
	("Chilan Berry", "Halves damage taken from a Normal-type attack. Single use.", 4),
	("Chill Drive", "Holder's Techno Blast is Ice type.", 5),
	("Chipped Pot", "Evolves Sinistea-Antique into Polteageist-Antique when used.", 8),
	("Choice Band", "Holder's Attack is 1.5x, but it can only select the first move it executes.", 3),
	("Choice Scarf", "Holder's Speed is 1.5x, but it can only select the first move it executes.", 4),
	("Choice Specs", "Holder's Sp. Atk is 1.5x, but it can only select the first move it executes.", 4),
	("Chople Berry", "Halves damage taken from a supereffective Fighting-type attack. Single use.", 4),
	("Claw Fossil", "Can be revived into Anorith.", 3),
	("Clear Amulet", "Prevents other Pokemon from lowering the holder's stat stages.", 9),
	("Clover Sweet", "Evolves Milcery into Alcremie when held and spun around.", 8),
	("Coba Berry", "Halves damage taken from a supereffective Flying-type attack. Single use.", 4),
	("Colbur Berry", "Halves damage taken from a supereffective Dark-type attack. Single use.", 4),
	("Cornerstone Mask", "Ogerpon-Cornerstone: 1.2x power attacks; Terastallize to gain Embody Aspect.", 9),
	("Cornn Berry", "Cannot be eaten by the holder. No effect when eaten with Bug Bite or Pluck.", 3),
	("Cover Fossil", "Can be revived into Tirtouga.", 5),
	("Covert Cloak", "Holder is not affected by the secondary effect of another Pokemon's attack.", 9),
	("Cracked Pot", "Evolves Sinistea into Polteageist when used.", 8),
	("Custap Berry", "Holder moves first in its priority bracket when at 1/4 max HP or less. Single use.", 4),
	("Damp Rock", "Holder's use of Rain Dance lasts 8 turns instead of 5.", 4),
	("Dark Gem", "Holder's first successful Dark-type attack will have 1.3x power. Single use.", 5),
	("Dark Memory", "Holder's Multi-Attack is Dark type.", 7),
	("Darkinium Z", "If holder has a Dark move, this item allows it to use a Dark Z-Move.", 7),
	("Dawn Stone", "Evolves male Kirlia into Gallade and female Snorunt into Froslass when used.", 4),
	("Decidium Z", "If held by a Decidueye with Spirit Shackle, it can use Sinister Arrow Raid.", 7),
	("Deep Sea Scale", "If held by a Clamperl, its Sp. Def is doubled. Evolves Clamperl into Gorebyss when traded.", 3),
	("Deep Sea Tooth", "If held by a Clamperl, its Sp. Atk is doubled. Evolves Clamperl into Huntail when traded.", 3),
	("Destiny Knot", "If holder becomes infatuated, the other Pokemon also becomes infatuated.", 4),
	("Diancite", "If held by a Diancie, this item allows it to Mega Evolve in battle.", 6),
	("Dive Ball", "A Poke Ball that works especially well on Pokemon that live underwater.", 3),
	("Dome Fossil", "Can be revived into Kabuto.", 3),
	("Douse Drive", "Holder's Techno Blast is Water type.", 5),
	("Draco Plate", "Holder's Dragon-type attacks have 1.2x power. Judgment is Dragon type.", 4),
	("Dragon Fang", "Holder's Dragon-type attacks have 1.2x power.", 2),
	("Dragon Gem", "Holder's first successful Dragon-type attack will have 1.3x power. Single use.", 5),
	("Dragon Memory", "Holder's Multi-Attack is Dragon type.", 7),
	("Dragon Scale", "Evolves Seadra into Kingdra when traded.", 2),
	("Dragonium Z", "If holder has a Dragon move, this item allows it to use a Dragon Z-Move.", 7),
	("Dread Plate", "Holder's Dark-type attacks have 1.2x power. Judgment is Dark type.", 4),
	("Dream Ball", "A Poke Ball that makes it easier to catch wild Pokémon while they're asleep.", 5),
	("Dubious Disc", "Evolves Porygon2 into Porygon-Z when traded.", 4),
	("Durin Berry", "Cannot be eaten by the holder. No effect when eaten with Bug Bite or Pluck.", 3),
	("Dusk Ball", "A Poke Ball that makes it easier to catch wild Pokemon at night or in caves.", 4),
	("Dusk Stone", "Evolves Murkrow into Honchkrow, Misdreavus into Mismagius, Lampent into Chandelure, and Doublade into Aegislash when used.", 4),
	("Earth Plate", "Holder's Ground-type attacks have 1.2x power. Judgment is Ground type.", 4),
	("Eevium Z", "If held by an Eevee with Last Resort, it can use Extreme Evoboost.", 7),
	("Eject Button", "If holder survives a hit, it immediately switches out to a chosen ally. Single use.", 5),
	("Eject Pack", "If the holder's stat stages are lowered, it switches to a chosen ally. Single use.", 8),
	("Electirizer", "Evolves Electabuzz into Electivire when traded.", 4),
	("Electric Gem", "Holder's first successful Electric-type attack will have 1.3x power. Single use.", 5),
	("Electric Memory", "Holder's Multi-Attack is Electric type.", 7),
	("Electric Seed", "If the terrain is Electric Terrain, raises holder's Defense by 1 stage. Single use.", 7),
	("Electrium Z", "If holder has an Electric move, this item allows it to use an Electric Z-Move.", 7),
	("Enigma Berry", "Restores 1/4 max HP after holder is hit by a supereffective move. Single use.", 3),
	("Eviolite", "If holder's species can evolve, its Defense and Sp. Def are 1.5x.", 5),
	("Expert Belt", "Holder's attacks that are super effective against the target do 1.2x damage.", 4),
	("Fairium Z", "If holder has a Fairy move, this item allows it to use a Fairy Z-Move.", 7),
	("Fairy Feather", "Holder's Fairy-type attacks have 1.2x power.", 9),
	("Fairy Gem", "Holder's first successful Fairy-type attack will have 1.3x power. Single use.", 6),
	("Fairy Memory", "Holder's Multi-Attack is Fairy type.", 7),
	("Fast Ball", "A Poke Ball that makes it easier to catch Pokemon which are quick to run away.", 2),
	("Fighting Gem", "Holder's first successful Fighting-type attack will have 1.3x power. Single use.", 5),
	("Fighting Memory", "Holder's Multi-Attack is Fighting type.", 7),
	("Fightinium Z", "If holder has a Fighting move, this item allows it to use a Fighting Z-Move.", 7),
	("Figy Berry", "Restores 1/3 max HP at 1/4 max HP or less; confuses if -Atk Nature. Single use.", 3),
	("Fire Gem", "Holder's first successful Fire-type attack will have 1.3x power. Single use.", 5),
	("Fire Memory", "Holder's Multi-Attack is Fire type.", 7),
	("Fire Stone", "Evolves Vulpix into Ninetales, Growlithe into Arcanine, Eevee into Flareon, and Pansear into Simisear when used.", 1),
	("Firium Z", "If holder has a Fire move, this item allows it to use a Fire Z-Move.", 7),
	("Fist Plate", "Holder's Fighting-type attacks have 1.2x power. Judgment is Fighting type.", 4),
	("Flame Orb", "At the end of every turn, this item attempts to burn the holder.", 4),
	("Flame Plate", "Holder's Fire-type attacks have 1.2x power. Judgment is Fire type.", 4),
	("Float Stone", "Holder's weight is halved.", 5),
	("Flower Sweet", "Evolves Milcery into Alcremie when held and spun around.", 8),
	("Flying Gem", "Holder's first successful Flying-type attack will have 1.3x power. Single use.", 5),
	("Flying Memory", "Holder's Multi-Attack is Flying type.", 7),
	("Flyinium Z", "If holder has a Flying move, this item allows it to use a Flying Z-Move.", 7),
	("Focus Band", "Holder has a 10% chance to survive an attack that would KO it with 1 HP.", 2),
	("Focus Sash", "If holder's HP is full, will survive an attack that would KO it with 1 HP. Single use.", 4),
	("Fossilized Bird", "Can revive into Dracozolt with Fossilized Drake or Arctozolt with Fossilized Dino.", 8),
	("Fossilized Dino", "Can revive into Arctovish with Fossilized Fish or Arctozolt with Fossilized Bird.", 8),
	("Fossilized Drake", "Can revive into Dracozolt with Fossilized Bird or Dracovish with Fossilized Fish.", 8),
	("Fossilized Fish", "Can revive into Dracovish with Fossilized Drake or Arctovish with Fossilized Dino.", 8),
	("Friend Ball", "A Poke Ball that makes caught Pokemon more friendly.", 2),
	("Full Incense", "Holder moves last in its priority bracket.", 4),
	("Galarica Cuff", "Evolves Galarian Slowpoke into Galarian Slowbro when used.", 8),
	("Galarica Wreath", "Evolves Galarian Slowpoke into Galarian Slowking when used.", 8),
	("Galladite", "If held by a Gallade, this item allows it to Mega Evolve in battle.", 6),
	("Ganlon Berry", "Raises holder's Defense by 1 stage when at 1/4 max HP or less. Single use.", 3),
	("Garchompite", "If held by a Garchomp, this item allows it to Mega Evolve in battle.", 6),
	("Gardevoirite", "If held by a Gardevoir, this item allows it to Mega Evolve in battle.", 6),
	("Gengarite", "If held by a Gengar, this item allows it to Mega Evolve in battle.", 6),
	("Ghost Gem", "Holder's first successful Ghost-type attack will have 1.3x power. Single use.", 5),
	("Ghost Memory", "Holder's Multi-Attack is Ghost type.", 7),
	("Ghostium Z", "If holder has a Ghost move, this item allows it to use a Ghost Z-Move.", 7),
	("Glalitite", "If held by a Glalie, this item allows it to Mega Evolve in battle.", 6),
	("Gold Bottle Cap", "Used for Hyper Training. All of a Pokemon's stats are calculated with an IV of 31.", 7),
	("Grass Gem", "Holder's first successful Grass-type attack will have 1.3x power. Single use.", 5),
	("Grass Memory", "Holder's Multi-Attack is Grass type.", 7),
	("Grassium Z", "If holder has a Grass move, this item allows it to use a Grass Z-Move.", 7),
	("Grassy Seed", "If the terrain is Grassy Terrain, raises holder's Defense by 1 stage. Single use.", 7),
	("Great Ball", "A high-performance Ball that provides a higher catch rate than a Poke Ball.", 1),
	("Grepa Berry", "Cannot be eaten by the holder. No effect when eaten with Bug Bite or Pluck.", 3),
	("Grip Claw", "Holder's partial-trapping moves always last 7 turns.", 4),
	("Griseous Core", "If held by a Giratina, its Ghost- and Dragon-type attacks have 1.2x power.", 8),
	("Griseous Orb", "If held by a Giratina, its Ghost- and Dragon-type attacks have 1.2x power.", 4),
	("Ground Gem", "Holder's first successful Ground-type attack will have 1.3x power. Single use.", 5),
	("Ground Memory", "Holder's Multi-Attack is Ground type.", 7),
	("Groundium Z", "If holder has a Ground move, this item allows it to use a Ground Z-Move.", 7),
	("Gyaradosite", "If held by a Gyarados, this item allows it to Mega Evolve in battle.", 6),
	("Haban Berry", "Halves damage taken from a supereffective Dragon-type attack. Single use.", 4),
	("Hard Stone", "Holder's Rock-type attacks have 1.2x power.", 2),
	("Heal Ball", "A remedial Poke Ball that restores the caught Pokemon's HP and status problem.", 4),
	("Hearthflame Mask", "Ogerpon-Hearthflame: 1.2x power attacks; Terastallize to gain Embody Aspect.", 9),
	("Heat Rock", "Holder's use of Sunny Day lasts 8 turns instead of 5.", 4),
	("Heavy Ball", "A Poke Ball for catching very heavy Pokemon.", 2),
	("Heavy-Duty Boots", "When switching in, the holder is unaffected by hazards on its side of the field.", 8),
	("Helix Fossil", "Can be revived into Omanyte.", 3),
	("Heracronite", "If held by a Heracross, this item allows it to Mega Evolve in battle.", 6),
	("Hondew Berry", "Cannot be eaten by the holder. No effect when eaten with Bug Bite or Pluck.", 3),
	("Houndoominite", "If held by a Houndoom, this item allows it to Mega Evolve in battle.", 6),
	("Iapapa Berry", "Restores 1/3 max HP at 1/4 max HP or less; confuses if -Def Nature. Single use.", 3),
	("Ice Gem", "Holder's first successful Ice-type attack will have 1.3x power. Single use.", 5),
	("Ice Memory", "Holder's Multi-Attack is Ice type.", 7),
	("Ice Stone", "Evolves Alolan Sandshrew into Alolan Sandslash, Alolan Vulpix into Alolan Ninetales, Eevee into Glaceon, and Galarian Darumaka into Galarian Darmanitan when used.", 7),
	("Icicle Plate", "Holder's Ice-type attacks have 1.2x power. Judgment is Ice type.", 4),
	("Icium Z", "If holder has an Ice move, this item allows it to use an Ice Z-Move.", 7),
	("Icy Rock", "Holder's use of Hail lasts 8 turns instead of 5.", 4),
	("Incinium Z", "If held by an Incineroar with Darkest Lariat, it can use Malicious Moonsault.", 7),
	("Insect Plate", "Holder's Bug-type attacks have 1.2x power. Judgment is Bug type.", 4),
	("Iron Ball", "Holder is grounded, Speed halved. If Flying type, takes neutral Ground damage.", 4),
	("Iron Plate", "Holder's Steel-type attacks have 1.2x power. Judgment is Steel type.", 4),
	("Jaboca Berry", "If holder is hit by a physical move, attacker loses 1/8 of its max HP. Single use.", 4),
	("Jaw Fossil", "Can be revived into Tyrunt.", 6),
	("Kasib Berry", "Halves damage taken from a supereffective Ghost-type attack. Single use.", 4),
	("Kebia Berry", "Halves damage taken from a supereffective Poison-type attack. Single use.", 4),
	("Kee Berry", "Raises holder's Defense by 1 stage after it is hit by a physical attack. Single use.", 6),
	("Kelpsy Berry", "Cannot be eaten by the holder. No effect when eaten with Bug Bite or Pluck.", 3),
	("Kangaskhanite", "If held by a Kangaskhan, this item allows it to Mega Evolve in battle.", 6),
	("King's Rock", "Holder's attacks without a chance to make the target flinch gain a 10% chance to make the target flinch. Evolves Poliwhirl into Politoed and Slowpoke into Slowking when traded.", 2),
	("Kommonium Z", "If held by a Kommo-o with Clanging Scales, it can use Clangorous Soulblaze.", 7),
	("Lagging Tail", "Holder moves last in its priority bracket.", 4),
	("Lansat Berry", "Holder gains the Focus Energy effect when at 1/4 max HP or less. Single use.", 3),
	("Latiasite", "If held by a Latias, this item allows it to Mega Evolve in battle.", 6),
	("Latiosite", "If held by a Latios, this item allows it to Mega Evolve in battle.", 6),
	("Lax Incense", "The accuracy of attacks against the holder is 0.9x.", 3),
	("Leaf Stone", "Evolves Gloom into Vileplume, Weepinbell into Victreebel, Exeggcute into Exeggutor or Alolan Exeggutor, Eevee into Leafeon, Nuzleaf into Shiftry, and Pansage into Simisage when used.", 1),
	("Leek", "If held by a Farfetch’d or Sirfetch’d, its critical hit ratio is raised by 2 stages.", 8),
	("Leftovers", "At the end of every turn, holder restores 1/16 of its max HP.", 2),
	("Leppa Berry", "Restores 10 PP to the first of the holder's moves to reach 0 PP. Single use.", 3),
	("Level Ball", "A Poke Ball for catching Pokemon that are a lower level than your own.", 2),
	("Liechi Berry", "Raises holder's Attack by 1 stage when at 1/4 max HP or less. Single use.", 3),
	("Life Orb", "Holder's attacks do 1.3x damage, and it loses 1/10 its max HP after the attack.", 4),
	("Light Ball", "If held by a Pikachu, its Attack and Sp. Atk are doubled.", 2),
	("Light Clay", "Holder's use of Aurora Veil, Light Screen, or Reflect lasts 8 turns instead of 5.", 4),
	("Loaded Dice", "Holder's moves that hit 2-5 times hit 4-5 times; Population Bomb hits 4-10 times.", 9),
	("Lopunnite", "If held by a Lopunny, this item allows it to Mega Evolve in battle.", 6),
	("Love Ball", "Poke Ball for catching Pokemon that are the opposite gender of your Pokemon.", 2),
	("Love Sweet", "Evolves Milcery into Alcremie when held and spun around.", 8),
	("Lucarionite", "If held by a Lucario, this item allows it to Mega Evolve in battle.", 6),
	("Lucky Punch", "If held by a Chansey, its critical hit ratio is raised by 2 stages.", 2),
	("Lum Berry", "Holder cures itself if it has a non-volatile status or is confused. Single use.", 3),
	("Luminous Moss", "Raises holder's Sp. Def by 1 stage if hit by a Water-type attack. Single use.", 6),
	("Lunalium Z", "Lunala or Dawn Wings Necrozma with Moongeist Beam can use a special Z-Move.", 7),
	("Lure Ball", "A Poke Ball for catching Pokemon hooked by a Rod when fishing.", 2),
	("Lustrous Globe", "If held by a Palkia, its Water- and Dragon-type attacks have 1.2x power.", 8),
	("Lustrous Orb", "If held by a Palkia, its Water- and Dragon-type attacks have 1.2x power.", 4),
	("Luxury Ball", "A comfortable Poke Ball that makes a caught wild Pokemon quickly grow friendly.", 3),
	("Lycanium Z", "If held by a Lycanroc forme with Stone Edge, it can use Splintered Stormshards.", 7),
	("Macho Brace", "Holder's Speed is halved. The Klutz Ability does not ignore this effect.", 3),
	("Magmarizer", "Evolves Magmar into Magmortar when traded.", 4),
	("Magnet", "Holder's Electric-type attacks have 1.2x power.", 2),
	("Mago Berry", "Restores 1/3 max HP at 1/4 max HP or less; confuses if -Spe Nature. Single use.", 3),
	("Magost Berry", "Cannot be eaten by the holder. No effect when eaten with Bug Bite or Pluck.", 3),
	("Mail", "Cannot be given to or taken from a Pokemon, except by Covet/Knock Off/Thief.", 2),
	("Malicious Armor", "Evolves Charcadet into Ceruledge when used.", 9),
	("Manectite", "If held by a Manectric, this item allows it to Mega Evolve in battle.", 6),
	("Maranga Berry", "Raises holder's Sp. Def by 1 stage after it is hit by a special attack. Single use.", 6),
	("Marshadium Z", "If held by Marshadow with Spectral Thief, it can use Soul-Stealing 7-Star Strike.", 7),
	("Master Ball", "The best Ball with the ultimate performance. It will catch any wild Pokemon.", 1),
	("Masterpiece Teacup", "Evolves Poltchageist-Artisan into Sinistcha-Masterpiece when used.", 9),
	("Mawilite", "If held by a Mawile, this item allows it to Mega Evolve in battle.", 6),
	("Meadow Plate", "Holder's Grass-type attacks have 1.2x power. Judgment is Grass type.", 4),
	("Medichamite", "If held by a Medicham, this item allows it to Mega Evolve in battle.", 6),
	("Mental Herb", "Cures holder of Attract, Disable, Encore, Heal Block, Taunt, Torment. Single use.", 3),
	("Metagrossite", "If held by a Metagross, this item allows it to Mega Evolve in battle.", 6),
	("Metal Coat", "Holder's Steel-type attacks have 1.2x power. Evolves Onix into Steelix and Scyther into Scizor when traded.", 2),
	("Metal Powder", "If held by a Ditto that hasn't Transformed, its Defense is doubled.", 2),
	("Metronome", "Damage of moves used on consecutive turns is increased. Max 2x after 5 turns.", 4),
	("Mewnium Z", "If held by a Mew with Psychic, it can use Genesis Supernova.", 7),
	("Mewtwonite X", "If held by a Mewtwo, this item allows it to Mega Evolve in battle.", 6),
	("Mewtwonite Y", "If held by a Mewtwo, this item allows it to Mega Evolve in battle.", 6),
	("Micle Berry", "Holder's next move has 1.2x accuracy when at 1/4 max HP or less. Single use.", 4),
	("Mimikium Z", "If held by a Mimikyu with Play Rough, it can use Let's Snuggle Forever.", 7),
	("Mind Plate", "Holder's Psychic-type attacks have 1.2x power. Judgment is Psychic type.", 4),
	("Miracle Seed", "Holder's Grass-type attacks have 1.2x power.", 2),
	("Mirror Herb", "When an opposing Pokemon raises a stat stage, the holder copies it. Single use.", 9),
	("Misty Seed", "If the terrain is Misty Terrain, raises holder's Sp. Def by 1 stage. Single use.", 7),
	("Moon Ball", "A Poke Ball for catching Pokemon that evolve using the Moon Stone.", 2),
	("Moon Stone", "Evolves Nidorina into Nidoqueen, Nidorino into Nidoking, Clefairy into Clefable, Jigglypuff into Wigglytuff, Skitty into Delcatty, and Munna into Musharna when used.", 1),
	("Muscle Band", "Holder's physical attacks have 1.1x power.", 4),
	("Mystic Water", "Holder's Water-type attacks have 1.2x power.", 2),
	("Nanab Berry", "Cannot be eaten by the holder. No effect when eaten with Bug Bite or Pluck.", 3),
	("Nest Ball", "A Poke Ball that works especially well on weaker Pokemon in the wild.", 3),
	("Net Ball", "A Poke Ball that works especially well on Water- and Bug-type Pokemon.", 3),
	("Never-Melt Ice", "Holder's Ice-type attacks have 1.2x power.", 2),
	("Nomel Berry", "Cannot be eaten by the holder. No effect when eaten with Bug Bite or Pluck.", 3),
	("Normal Gem", "Holder's first successful Normal-type attack will have 1.3x power. Single use.", 5),
	("Normalium Z", "If holder has a Normal move, this item allows it to use a Normal Z-Move.", 7),
	("Occa Berry", "Halves damage taken from a supereffective Fire-type attack. Single use.", 4),
	("Odd Incense", "Holder's Psychic-type attacks have 1.2x power.", 4),
	("Old Amber", "Can be revived into Aerodactyl.", 3),
	("Oran Berry", "Restores 10 HP when at 1/2 max HP or less. Single use.", 3),
	("Oval Stone", "Evolves Happiny into Chansey when held and leveled up during the day.", 4),
	("Pamtre Berry", "Cannot be eaten by the holder. No effect when eaten with Bug Bite or Pluck.", 3),
	("Park Ball", "A special Poke Ball for the Pal Park.", 4),
	("Passho Berry", "Halves damage taken from a supereffective Water-type attack. Single use.", 4),
	("Payapa Berry", "Halves damage taken from a supereffective Psychic-type attack. Single use.", 4),
	("Pecha Berry", "Holder is cured if it is poisoned. Single use.", 3),
	("Persim Berry", "Holder is cured if it is confused. Single use.", 3),
	("Petaya Berry", "Raises holder's Sp. Atk by 1 stage when at 1/4 max HP or less. Single use.", 3),
	("Pidgeotite", "If held by a Pidgeot, this item allows it to Mega Evolve in battle.", 6),
	("Pikanium Z", "If held by a Pikachu with Volt Tackle, it can use Catastropika.", 7),
	("Pikashunium Z", "If held by cap Pikachu with Thunderbolt, it can use 10,000,000 Volt Thunderbolt.", 7),
	("Pinap Berry", "Cannot be eaten by the holder. No effect when eaten with Bug Bite or Pluck.", 3),
	("Pinsirite", "If held by a Pinsir, this item allows it to Mega Evolve in battle.", 6),
	("Pixie Plate", "Holder's Fairy-type attacks have 1.2x power. Judgment is Fairy type.", 6),
	("Plume Fossil", "Can be revived into Archen.", 5),
	("Poison Barb", "Holder's Poison-type attacks have 1.2x power.", 2),
	("Poison Gem", "Holder's first successful Poison-type attack will have 1.3x power. Single use.", 5),
	("Poison Memory", "Holder's Multi-Attack is Poison type.", 7),
	("Poisonium Z", "If holder has a Poison move, this item allows it to use a Poison Z-Move.", 7),
	("Poke Ball", "A device for catching wild Pokemon. It is designed as a capsule system.", 1),
	("Pomeg Berry", "Cannot be eaten by the holder. No effect when eaten with Bug Bite or Pluck.", 3),
	("Power Anklet", "Holder's Speed is halved. The Klutz Ability does not ignore this effect.", 4),
	("Power Band", "Holder's Speed is halved. The Klutz Ability does not ignore this effect.", 4),
	("Power Belt", "Holder's Speed is halved. The Klutz Ability does not ignore this effect.", 4),
	("Power Bracer", "Holder's Speed is halved. The Klutz Ability does not ignore this effect.", 4),
	("Power Herb", "Holder's two-turn moves complete in one turn (except Sky Drop). Single use.", 4),
	("Power Lens", "Holder's Speed is halved. The Klutz Ability does not ignore this effect.", 4),
	("Power Weight", "Holder's Speed is halved. The Klutz Ability does not ignore this effect.", 4),
	("Premier Ball", "A rare Poke Ball that has been crafted to commemorate an event.", 3),
	("Primarium Z", "If held by a Primarina with Sparkling Aria, it can use Oceanic Operetta.", 7),
	("Prism Scale", "Evolves Feebas into Milotic when traded.", 5),
	("Protective Pads", "Holder's moves are protected from adverse contact effects, except Pickpocket.", 7),
	("Protector", "Evolves Rhydon into Rhyperior when traded.", 4),
	("Psychic Gem", "Holder's first successful Psychic-type attack will have 1.3x power. Single use.", 5),
	("Psychic Memory", "Holder's Multi-Attack is Psychic type.", 7),
	("Psychic Seed", "If the terrain is Psychic Terrain, raises holder's Sp. Def by 1 stage. Single use.", 7),
	("Psychium Z", "If holder has a Psychic move, this item allows it to use a Psychic Z-Move.", 7),
	("Punching Glove", "Holder's punch-based attacks have 1.1x power and do not make contact.", 9),
	("Qualot Berry", "Cannot be eaten by the holder. No effect when eaten with Bug Bite or Pluck.", 3),
	("Quick Ball", "A Poke Ball that provides a better catch rate at the start of a wild encounter.", 4),
	("Quick Claw", "Each turn, holder has a 20% chance to move first in its priority bracket.", 2),
	("Quick Powder", "If held by a Ditto that hasn't Transformed, its Speed is doubled.", 4),
	("Rabuta Berry", "Cannot be eaten by the holder. No effect when eaten with Bug Bite or Pluck.", 3),
	("Rare Bone", "No competitive use other than when used with Fling.", 4),
	("Rawst Berry", "Holder is cured if it is burned. Single use.", 3),
	("Razor Claw", "Holder's critical hit ratio is raised by 1 stage. Evolves Sneasel into Weavile when held and leveled up during the night.", 4),
	("Razor Fang", "Holder's attacks without a chance to make the target flinch gain a 10% chance to make the target flinch. Evolves Gligar into Gliscor when held and leveled up during the night.", 4),
	("Razz Berry", "Cannot be eaten by the holder. No effect when eaten with Bug Bite or Pluck.", 3),
	("Reaper Cloth", "Evolves Dusclops into Dusknoir when traded.", 4),
	("Red Card", "If holder survives a hit, attacker is forced to switch to a random ally. Single use.", 5),
	("Red Orb", "If held by a Groudon, this item triggers its Primal Reversion in battle.", 6),
	("Repeat Ball", "A Poke Ball that works well on Pokemon species that were previously caught.", 3),
	("Ribbon Sweet", "Evolves Milcery into Alcremie when held and spun around.", 8),
	("Rindo Berry", "Halves damage taken from a supereffective Grass-type attack. Single use.", 4),
	("Ring Target", "The holder's type immunities granted solely by its typing are negated.", 5),
	("Rock Gem", "Holder's first successful Rock-type attack will have 1.3x power. Single use.", 5),
	("Rock Incense", "Holder's Rock-type attacks have 1.2x power.", 4),
	("Rock Memory", "Holder's Multi-Attack is Rock type.", 7),
	("Rockium Z", "If holder has a Rock move, this item allows it to use a Rock Z-Move.", 7),
	("Rocky Helmet", "If holder is hit by a contact move, the attacker loses 1/6 of its max HP.", 5),
	("Room Service", "If Trick Room is active, the holder's Speed is lowered by 1 stage. Single use.", 8),
	("Root Fossil", "Can be revived into Lileep.", 3),
	("Rose Incense", "Holder's Grass-type attacks have 1.2x power.", 4),
	("Roseli Berry", "Halves damage taken from a supereffective Fairy-type attack. Single use.", 6),
	("Rowap Berry", "If holder is hit by a special move, attacker loses 1/8 of its max HP. Single use.", 4),
	("Rusted Shield", "If held by a Zamazenta, this item changes its forme to Crowned Shield.", 8),
	("Rusted Sword", "If held by a Zacian, this item changes its forme to Crowned Sword.", 8),
	("Sablenite", "If held by a Sableye, this item allows it to Mega Evolve in battle.", 6),
	("Sachet", "Evolves Spritzee into Aromatisse when traded.", 6),
	("Safari Ball", "A special Poke Ball that is used only in the Safari Zone and Great Marsh.", 1),
	("Safety Goggles", "Holder is immune to powder moves and damage from Sandstorm or Hail.", 6),
	("Sail Fossil", "Can be revived into Amaura.", 6),
	("Salac Berry", "Raises holder's Speed by 1 stage when at 1/4 max HP or less. Single use.", 3),
	("Salamencite", "If held by a Salamence, this item allows it to Mega Evolve in battle.", 6),
	("Sceptilite", "If held by a Sceptile, this item allows it to Mega Evolve in battle.", 6),
	("Scizorite", "If held by a Scizor, this item allows it to Mega Evolve in battle.", 6),
	("Scope Lens", "Holder's critical hit ratio is raised by 1 stage.", 2),
	("Sea Incense", "Holder's Water-type attacks have 1.2x power.", 3),
	("Sharp Beak", "Holder's Flying-type attacks have 1.2x power.", 2),
	("Sharpedonite", "If held by a Sharpedo, this item allows it to Mega Evolve in battle.", 6),
	("Shed Shell", "Holder may switch out even when trapped by another Pokemon, or by Ingrain.", 4),
	("Shell Bell", "After an attack, holder gains 1/8 of the damage in HP dealt to other Pokemon.", 3),
	("Shiny Stone", "Evolves Togetic into Togekiss, Roselia into Roserade, Minccino into Cinccino, and Floette into Florges when used.", 4),
	("Shock Drive", "Holder's Techno Blast is Electric type.", 5),
	("Shuca Berry", "Halves damage taken from a supereffective Ground-type attack. Single use.", 4),
	("Silk Scarf", "Holder's Normal-type attacks have 1.2x power.", 3),
	("Silver Powder", "Holder's Bug-type attacks have 1.2x power.", 2),
	("Sitrus Berry", "Restores 1/4 max HP when at 1/2 max HP or less. Single use.", 3),
	("Skull Fossil", "Can be revived into Cranidos.", 4),
	("Sky Plate", "Holder's Flying-type attacks have 1.2x power. Judgment is Flying type.", 4),
	("Slowbronite", "If held by a Slowbro, this item allows it to Mega Evolve in battle.", 6),
	("Smooth Rock", "Holder's use of Sandstorm lasts 8 turns instead of 5.", 4),
	("Snorlium Z", "If held by a Snorlax with Giga Impact, it can use Pulverizing Pancake.", 7),
	("Snowball", "Raises holder's Attack by 1 if hit by an Ice-type attack. Single use.", 6),
	("Soft Sand", "Holder's Ground-type attacks have 1.2x power.", 2),
	("Solganium Z", "Solgaleo or Dusk Mane Necrozma with Sunsteel Strike can use a special Z-Move.", 7),
	("Soul Dew", "If held by a Latias/Latios, its Dragon- and Psychic-type moves have 1.2x power.", 3),
	("Spell Tag", "Holder's Ghost-type attacks have 1.2x power.", 2),
	("Spelon Berry", "Cannot be eaten by the holder. No effect when eaten with Bug Bite or Pluck.", 3),
	("Splash Plate", "Holder's Water-type attacks have 1.2x power. Judgment is Water type.", 4),
	("Spooky Plate", "Holder's Ghost-type attacks have 1.2x power. Judgment is Ghost type.", 4),
	("Sport Ball", "A special Poke Ball for the Bug-Catching Contest.", 2),
	("Starf Berry", "Raises a random stat by 2 when at 1/4 max HP or less (not acc/eva). Single use.", 3),
	("Star Sweet", "Evolves Milcery into Alcremie when held and spun around.", 8),
	("Steelixite", "If held by a Steelix, this item allows it to Mega Evolve in battle.", 6),
	("Steel Gem", "Holder's first successful Steel-type attack will have 1.3x power. Single use.", 5),
	("Steel Memory", "Holder's Multi-Attack is Steel type.", 7),
	("Steelium Z", "If holder has a Steel move, this item allows it to use a Steel Z-Move.", 7),
	("Stick", "If held by a Farfetch’d, its critical hit ratio is raised by 2 stages.", 2),
	("Sticky Barb", "Each turn, holder loses 1/8 max HP. An attacker making contact can receive it.", 4),
	("Stone Plate", "Holder's Rock-type attacks have 1.2x power. Judgment is Rock type.", 4),
	("Strawberry Sweet", "Evolves Milcery into Alcremie when held and spun around.", 8),
	("Sun Stone", "Evolves Gloom into Bellossom, Sunkern into Sunflora, Cottonee into Whimsicott, Petilil into Lilligant, and Helioptile into Heliolisk when used.", 2),
	("Swampertite", "If held by a Swampert, this item allows it to Mega Evolve in battle.", 6),
	("Sweet Apple", "Evolves Applin into Appletun when used.", 8),
	("Syrupy Apple", "Evolves Applin into Dipplin when used.", 9),
	("Tamato Berry", "Cannot be eaten by the holder. No effect when eaten with Bug Bite or Pluck.", 3),
	("Tanga Berry", "Halves damage taken from a supereffective Bug-type attack. Single use.", 4),
	("Tapunium Z", "If held by a Tapu with Nature's Madness, it can use Guardian of Alola.", 7),
	("Tart Apple", "Evolves Applin into Flapple when used.", 8),
	("Terrain Extender", "Holder's use of Electric/Grassy/Misty/Psychic Terrain lasts 8 turns instead of 5.", 7),
	("Thick Club", "If held by a Cubone or a Marowak, its Attack is doubled.", 2),
	("Throat Spray", "Raises holder's Special Attack by 1 stage after it uses a sound move. Single use.", 8),
	("Thunder Stone", "Evolves Pikachu into Raichu or Alolan Raichu, Eevee into Jolteon, Eelektrik into Eelektross, and Charjabug into Vikavolt when used.", 1),
	("Timer Ball", "A Poke Ball that becomes better the more turns there are in a battle.", 3),
	("Toxic Orb", "At the end of every turn, this item attempts to badly poison the holder.", 4),
	("Toxic Plate", "Holder's Poison-type attacks have 1.2x power. Judgment is Poison type.", 4),
	("TR00", "Teaches certain Pokemon the move Swords Dance. One use.", 8),
	("TR01", "Teaches certain Pokemon the move Body Slam. One use.", 8),
	("TR02", "Teaches certain Pokemon the move Flamethrower. One use.", 8),
	("TR03", "Teaches certain Pokemon the move Hydro Pump. One use.", 8),
	("TR04", "Teaches certain Pokemon the move Surf. One use.", 8),
	("TR05", "Teaches certain Pokemon the move Ice Beam. One use.", 8),
	("TR06", "Teaches certain Pokemon the move Blizzard. One use.", 8),
	("TR07", "Teaches certain Pokemon the move Low Kick. One use.", 8),
	("TR08", "Teaches certain Pokemon the move Thunderbolt. One use.", 8),
	("TR09", "Teaches certain Pokemon the move Thunder. One use.", 8),
	("TR10", "Teaches certain Pokemon the move Earthquake. One use.", 8),
	("TR11", "Teaches certain Pokemon the move Psychic. One use.", 8),
	("TR12", "Teaches certain Pokemon the move Agility. One use.", 8),
	("TR13", "Teaches certain Pokemon the move Focus Energy. One use.", 8),
	("TR14", "Teaches certain Pokemon the move Metronome. One use.", 8),
	("TR15", "Teaches certain Pokemon the move Fire Blast. One use.", 8),
	("TR16", "Teaches certain Pokemon the move Waterfall. One use.", 8),
	("TR17", "Teaches certain Pokemon the move Amnesia. One use.", 8),
	("TR18", "Teaches certain Pokemon the move Leech Life. One use.", 8),
	("TR19", "Teaches certain Pokemon the move Tri Attack. One use.", 8),
	("TR20", "Teaches certain Pokemon the move Substitute. One use.", 8),
	("TR21", "Teaches certain Pokemon the move Reversal. One use.", 8),
	("TR22", "Teaches certain Pokemon the move Sludge Bomb. One use.", 8),
	("TR23", "Teaches certain Pokemon the move Spikes. One use.", 8),
	("TR24", "Teaches certain Pokemon the move Outrage. One use.", 8),
	("TR25", "Teaches certain Pokemon the move Psyshock. One use.", 8),
	("TR26", "Teaches certain Pokemon the move Endure. One use.", 8),
	("TR27", "Teaches certain Pokemon the move Sleep Talk. One use.", 8),
	("TR28", "Teaches certain Pokemon the move Megahorn. One use.", 8),
	("TR29", "Teaches certain Pokemon the move Baton Pass. One use.", 8),
	("TR30", "Teaches certain Pokemon the move Encore. One use.", 8),
	("TR31", "Teaches certain Pokemon the move Iron Tail. One use.", 8),
	("TR32", "Teaches certain Pokemon the move Crunch. One use.", 8),
	("TR33", "Teaches certain Pokemon the move Shadow Ball. One use.", 8),
	("TR34", "Teaches certain Pokemon the move Future Sight. One use.", 8),
	("TR35", "Teaches certain Pokemon the move Uproar. One use.", 8),
	("TR36", "Teaches certain Pokemon the move Heat Wave. One use.", 8),
	("TR37", "Teaches certain Pokemon the move Taunt. One use.", 8),
	("TR38", "Teaches certain Pokemon the move Trick. One use.", 8),
	("TR39", "Teaches certain Pokemon the move Superpower. One use.", 8),
	("TR40", "Teaches certain Pokemon the move Skill Swap. One use.", 8),
	("TR41", "Teaches certain Pokemon the move Blaze Kick. One use.", 8),
	("TR42", "Teaches certain Pokemon the move Hyper Voice. One use.", 8),
	("TR43", "Teaches certain Pokemon the move Overheat. One use.", 8),
	("TR44", "Teaches certain Pokemon the move Cosmic Power. One use.", 8),
	("TR45", "Teaches certain Pokemon the move Muddy Water. One use.", 8),
	("TR46", "Teaches certain Pokemon the move Iron Defense. One use.", 8),
	("TR47", "Teaches certain Pokemon the move Dragon Claw. One use.", 8),
	("TR48", "Teaches certain Pokemon the move Bulk Up. One use.", 8),
	("TR49", "Teaches certain Pokemon the move Calm Mind. One use.", 8),
	("TR50", "Teaches certain Pokemon the move Leaf Blade. One use.", 8),
	("TR51", "Teaches certain Pokemon the move Dragon Dance. One use.", 8),
	("TR52", "Teaches certain Pokemon the move Gyro Ball. One use.", 8),
	("TR53", "Teaches certain Pokemon the move Close Combat. One use.", 8),
	("TR54", "Teaches certain Pokemon the move Toxic Spikes. One use.", 8),
	("TR55", "Teaches certain Pokemon the move Flare Blitz. One use.", 8),
	("TR56", "Teaches certain Pokemon the move Aura Sphere. One use.", 8),
	("TR57", "Teaches certain Pokemon the move Poison Jab. One use.", 8),
	("TR58", "Teaches certain Pokemon the move Dark Pulse. One use.", 8),
	("TR59", "Teaches certain Pokemon the move Seed Bomb. One use.", 8),
	("TR60", "Teaches certain Pokemon the move X-Scissor. One use.", 8),
	("TR61", "Teaches certain Pokemon the move Bug Buzz. One use.", 8),
	("TR62", "Teaches certain Pokemon the move Dragon Pulse. One use.", 8),
	("TR63", "Teaches certain Pokemon the move Power Gem. One use.", 8),
	("TR64", "Teaches certain Pokemon the move Focus Blast. One use.", 8),
	("TR65", "Teaches certain Pokemon the move Energy Ball. One use.", 8),
	("TR66", "Teaches certain Pokemon the move Brave Bird. One use.", 8),
	("TR67", "Teaches certain Pokemon the move Earth Power. One use.", 8),
	("TR68", "Teaches certain Pokemon the move Nasty Plot. One use.", 8),
	("TR69", "Teaches certain Pokemon the move Zen Headbutt. One use.", 8),
	("TR70", "Teaches certain Pokemon the move Flash Cannon. One use.", 8),
	("TR71", "Teaches certain Pokemon the move Leaf Storm. One use.", 8),
	("TR72", "Teaches certain Pokemon the move Power Whip. One use.", 8),
	("TR73", "Teaches certain Pokemon the move Gunk Shot. One use.", 8),
	("TR74", "Teaches certain Pokemon the move Iron Head. One use.", 8),
	("TR75", "Teaches certain Pokemon the move Stone Edge. One use.", 8),
	("TR76", "Teaches certain Pokemon the move Stealth Rock. One use.", 8),
	("TR77", "Teaches certain Pokemon the move Grass Knot. One use.", 8),
	("TR78", "Teaches certain Pokemon the move Sludge Wave. One use.", 8),
	("TR79", "Teaches certain Pokemon the move Heavy Slam. One use.", 8),
	("TR80", "Teaches certain Pokemon the move Electro Ball. One use.", 8),
	("TR81", "Teaches certain Pokemon the move Foul Play. One use.", 8),
	("TR82", "Teaches certain Pokemon the move Stored Power. One use.", 8),
	("TR83", "Teaches certain Pokemon the move Ally Switch. One use.", 8),
	("TR84", "Teaches certain Pokemon the move Scald. One use.", 8),
	("TR85", "Teaches certain Pokemon the move Work Up. One use.", 8),
	("TR86", "Teaches certain Pokemon the move Wild Charge. One use.", 8),
	("TR87", "Teaches certain Pokemon the move Drill Run. One use.", 8),
	("TR88", "Teaches certain Pokemon the move Heat Crash. One use.", 8),
	("TR89", "Teaches certain Pokemon the move Hurricane. One use.", 8),
	("TR90", "Teaches certain Pokemon the move Play Rough. One use.", 8),
	("TR91", "Teaches certain Pokemon the move Venom Drench. One use.", 8),
	("TR92", "Teaches certain Pokemon the move Dazzling Gleam. One use.", 8),
	("TR93", "Teaches certain Pokemon the move Darkest Lariat. One use.", 8),
	("TR94", "Teaches certain Pokemon the move High Horsepower. One use.", 8),
	("TR95", "Teaches certain Pokemon the move Throat Chop. One use.", 8),
	("TR96", "Teaches certain Pokemon the move Pollen Puff. One use.", 8),
	("TR97", "Teaches certain Pokemon the move Psychic Fangs. One use.", 8),
	("TR98", "Teaches certain Pokemon the move Liquidation. One use.", 8),
	("TR99", "Teaches certain Pokemon the move Body Press. One use.", 8),
	("Twisted Spoon", "Holder's Psychic-type attacks have 1.2x power.", 2),
	("Tyranitarite", "If held by a Tyranitar, this item allows it to Mega Evolve in battle.", 6),
	("Ultra Ball", "An ultra-performance Ball that provides a higher catch rate than a Great Ball.", 1),
	("Ultranecrozium Z", "Dusk Mane/Dawn Wings Necrozma: Ultra Burst, then Z-Move w/ Photon Geyser.", 7),
	("Unremarkable Teacup", "Evolves Poltchageist into Sinistcha when used.", 9),
	("Up-Grade", "Evolves Porygon into Porygon2 when traded.", 2),
	("Utility Umbrella", "The holder ignores rain- and sun-based effects. Damage and accuracy calculations from attacks used by the holder are affected by rain and sun, but not attacks used against the holder.", 8),
	("Venusaurite", "If held by a Venusaur, this item allows it to Mega Evolve in battle.", 6),
	("Wacan Berry", "Halves damage taken from a supereffective Electric-type attack. Single use.", 4),
	("Water Gem", "Holder's first successful Water-type attack will have 1.3x power. Single use.", 5),
	("Water Memory", "Holder's Multi-Attack is Water type.", 7),
	("Water Stone", "Evolves Poliwhirl into Poliwrath, Shellder into Cloyster, Staryu into Starmie, Eevee into Vaporeon, Lombre into Ludicolo, and Panpour into Simipour when used.", 1),
	("Waterium Z", "If holder has a Water move, this item allows it to use a Water Z-Move.", 7),
	("Watmel Berry", "Cannot be eaten by the holder. No effect when eaten with Bug Bite or Pluck.", 3),
	("Wave Incense", "Holder's Water-type attacks have 1.2x power.", 4),
	("Weakness Policy", "If holder is hit super effectively, raises Attack, Sp. Atk by 2 stages. Single use.", 6),
	("Wellspring Mask", "Ogerpon-Wellspring: 1.2x power attacks; Terastallize to gain Embody Aspect.", 9),
	("Wepear Berry", "Cannot be eaten by the holder. No effect when eaten with Bug Bite or Pluck.", 3),
	("Whipped Dream", "Evolves Swirlix into Slurpuff when traded.", 6),
	("White Herb", "Restores all lowered stat stages to 0 when one is less than 0. Single use.", 3),
	("Wide Lens", "The accuracy of attacks by the holder is 1.1x.", 4),
	("Wiki Berry", "Restores 1/3 max HP at 1/4 max HP or less; confuses if -SpA Nature. Single use.", 3),
	("Wise Glasses", "Holder's special attacks have 1.1x power.", 4),
	("Yache Berry", "Halves damage taken from a supereffective Ice-type attack. Single use.", 4),
	("Zap Plate", "Holder's Electric-type attacks have 1.2x power. Judgment is Electric type.", 4),
	("Zoom Lens", "The accuracy of attacks by the holder is 1.2x if it moves after its target.", 4),
	("Berserk Gene", "(Gen 2) On switch-in, raises holder's Attack by 2 and confuses it. Single use.", 2),
	("Berry", "(Gen 2) Restores 10 HP when at 1/2 max HP or less. Single use.", 2),
	("Bitter Berry", "(Gen 2) Holder is cured if it is confused. Single use.", 2),
	("Burnt Berry", "(Gen 2) Holder is cured if it is frozen. Single use.", 2),
	("Gold Berry", "(Gen 2) Restores 30 HP when at 1/2 max HP or less. Single use.", 2),
	("Ice Berry", "(Gen 2) Holder is cured if it is burned. Single use.", 2),
	("Mint Berry", "(Gen 2) Holder wakes up if it is asleep. Single use.", 2),
	("Miracle Berry", "(Gen 2) Holder cures itself if it is confused or has a status condition. Single use.", 2),
	("Mystery Berry", "(Gen 2) Restores 5 PP to the first of the holder's moves to reach 0 PP. Single use.", 2),
	("Pink Bow", "(Gen 2) Holder's Normal-type attacks have 1.1x power.", 2),
	("Polkadot Bow", "(Gen 2) Holder's Normal-type attacks have 1.1x power.", 2),
	("PRZ Cure Berry", "(Gen 2) Holder cures itself if it is paralyzed. Single use.", 2),
	("PSN Cure Berry", "(Gen 2) Holder is cured if it is poisoned. Single use.", 2),
	("Crucibellite", "If held by a Crucibelle, this item allows it to Mega Evolve in battle.", 6),
	("Vile Vial", "If held by a Venomicon, its Poison- and Flying-type attacks have 1.2x power.", 8)
);