INSERT INTO abilities (name, description, generation) VALUES
(
	("No Ability", "Does nothing.", 1),
	("Adaptability", "This Pokemon''s moves that match one of its types have a same-type attack bonus (STAB) of 2 instead of 1.5.", 1),
	("Aerilate", "This Pokemon''s Normal-type moves become Flying-type moves and have their power multiplied by 1.2. This effect comes after other effects that change a mov'e's type, but before Ion Deluge and Electri'fy's effects.", 1),
	("Aftermath", "If this Pokemon is knocked out with a contact move, that move''s user loses 1/4 of its maximum HP, rounded down. If any active Pokemon has the Damp Ability, this effect is prevented.", 1),
	("Air Lock", "While this Pokemon is active, the effects of weather conditions are disabled.", 1),
	("Analytic", "The power of this Pokemon''s move is multiplied by 1.3 if it is the last to move in a turn. Does not affect Doom Desire and Future Sight.", 1),
	("Anger Point", "If this Pokemon, but not its substitute, is struck by a critical hit, its Attack is raised by 12 stages.", 1),
	("Anger Shell", "When this Pokemon has more than 1/2 its maximum HP and takes damage from an attack bringing it to 1/2 or less of its maximum HP, its Attack, Special Attack, and Speed are raised by 1 stage, and its Defense and Special Defense are lowered by 1 stage. This effect applies after all hits from a multi-hit move. This effect is prevented if the move had a secondary effect removed by the Sheer Force Ability.", 1),
	("Anticipation", "On switch-in, this Pokemon is alerted if any opposing Pokemon has an attack that is super effective against this Pokemon, or an OHKO move. This effect considers any move that deals direct damage as an attacking move of its respective type, Hidden Power counts as its determined type, and Judgment, Multi-Attack, Natural Gift, Revelation Dance, Techno Blast, and Weather Ball are considered Normal-type moves.", 1),
	("Arena Trap", "Prevents opposing Pokemon from choosing to switch out unless they are airborne, are holding a Shed Shell, or are a Ghost type.", 1),
	("Armor Tail", "Priority moves used by opposing Pokemon targeting this Pokemon or its allies are prevented from having an effect.", 1),
	("Aroma Veil", "This Pokemon and its allies cannot become affected by Attract, Disable, Encore, Heal Block, Taunt, or Torment.", 1),
	("As One (Glastrier)", "Combination of the Unnerve and Chilling Neigh Abilities.", 1),
	("As One (Spectrier)", "Combination of the Unnerve and Grim Neigh Abilities.", 1),
	("Aura Break", "While this Pokemon is active, the effects of the Dark Aura and Fairy Aura Abilities are reversed, multiplying the power of Dark- and Fairy-type moves, respectively, by 3/4 instead of 1.33.", 1),
	("Bad Dreams", "Causes opposing Pokemon to lose 1/8 of their maximum HP, rounded down, at the end of each turn if they are asleep.", 1),
	("Ball Fetch", "No competitive use.", 1),
	("Battery", "This Pokemon''s allies have the power of their special attacks multiplied by 1.3.", 1),
	("Battle Armor", "This Pokemon cannot be struck by a critical hit.", 1),
	("Battle Bond", "If this Pokemon is a Greninja, its Attack, Special Attack, and Speed are raised by 1 stage if it attacks and knocks out another Pokemon. This effect can only happen once per battle.", 1),
	("Beads of Ruin", "Active Pokemon without this Ability have their Special Defense multiplied by 0.75.", 1),
	("Beast Boost", "This Pokemon''s highest stat is raised by 1 stage if it attacks and knocks out another Pokemon. Stat stage changes are not considered. If multiple stats are tied, Attack, Defense, Special Attack, Special Defense, and Speed are prioritized in that order.", 1),
	("Berserk", "When this Pokemon has more than 1/2 its maximum HP and takes damage from an attack bringing it to 1/2 or less of its maximum HP, its Special Attack is raised by 1 stage. This effect applies after all hits from a multi-hit move. This effect is prevented if the move had a secondary effect removed by the Sheer Force Ability.", 1),
	("Big Pecks", "Prevents other Pokemon from lowering this Pokemon''s Defense stat stage.", 1),
	("Blaze", "When this Pokemon has 1/3 or less of its maximum HP, rounded down, its offensive stat is multiplied by 1.5 while using a Fire-type attack.", 1),
	("Bulletproof", "This Pokemon is immune to bullet moves.", 1),
	("Cheek Pouch", "If this Pokemon eats a held Berry, it restores 1/3 of its maximum HP, rounded down, in addition to the Berry''s effect. This effect can also activate after the effects of Bug Bite, Fling, Pluck, Stuff Cheeks, and Teatime if the eaten Berry had an effect on this Pokemon.", 1),
	("Chilling Neigh", "This Pokemon''s Attack is raised by 1 stage if it attacks and knocks out another Pokemon.", 1),
	("Chlorophyll", "If Sunny Day is active, this Pokemon''s Speed is doubled. This effect is prevented if this Pokemon is holding a Utility Umbrella.", 1),
	("Clear Body", "Prevents other Pokemon from lowering this Pokemon''s stat stages.", 1),
	("Cloud Nine", "While this Pokemon is active, the effects of weather conditions are disabled.", 1),
	("Color Change", "This Pokemon''s type changes to match the type of the last move that hit it, unless that type is already one of its types. This effect applies after all hits from a multi-hit move. This effect is prevented if the move had a secondary effect removed by the Sheer Force Ability.", 1),
	("Comatose", "This Pokemon is considered to be asleep and cannot become affected by a non-volatile status condition or Yawn.", 1),
	("Commander", "If this Pokemon is a Tatsugiri and a Dondozo is an active ally, this Pokemon goes into the Dondozo''s mouth. The Dondozo has its Attack, Special Attack, Speed, Defense, and Special Defense raised by 2 stages. During the effect, the Dondozo cannot be switched out, this Pokemon cannot select an action, and attacks targeted at this Pokemon will be avoided but it will still take indirect damage. If this Pokemon faints during the effect, a Pokemon can be switched in as a replacement but the Dondozo remains unable to be switched out. If the Dondozo faints during the effect, this Pokemon regains the ability to select an action.", 1),
	("Competitive", "This Pokemon''s Special Attack is raised by 2 stages for each of its stat stages that is lowered by an opposing Pokemon.", 1),
	("Compound Eyes", "This Pokemon''s moves have their accuracy multiplied by 1.3.", 1),
	("Contrary", "If this Pokemon has a stat stage raised it is lowered instead, and vice versa.", 1),
	("Corrosion", "This Pokemon can poison or badly poison a Pokemon regardless of its typing.", 1),
	("Costar", "On switch-in, this Pokemon copies all of its ally''s stat stage changes.", 1),
	("Cotton Down", "When this Pokemon is hit by an attack, the Speed of all other Pokemon on the field is lowered by 1 stage.", 1),
	("Cud Chew", "If this Pokemon eats a Berry, it will eat that Berry again at the end of the next turn.", 1),
	("Curious Medicine", "On switch-in, this Pokemon''s allies have their stat stages reset to 0.", 1),
	("Cursed Body", "If this Pokemon is hit by an attack, there is a 30% chance that move gets disabled unless one of the attacker''s moves is already disabled.", 1),
	("Cute Charm", "There is a 30% chance a Pokemon making contact with this Pokemon will become infatuated if it is of the opposite gender.", 1),
	("Damp", "While this Pokemon is active, Explosion, Mind Blown, Misty Explosion, Self-Destruct, and the Aftermath Ability are prevented from having an effect.", 1),
	("Dancer", "After another Pokemon uses a dance move, this Pokemon uses the same move. The copied move is subject to all effects that can prevent a move from being executed. A move used through this Ability cannot be copied again by other Pokemon with this Ability.", 1),
	("Dark Aura", "While this Pokemon is active, the power of Dark-type moves used by active Pokemon is multiplied by 1.33.", 1),
	("Dauntless Shield", "On switch-in, this Pokemon''s Defense is raised by 1 stage. Once per battle.", 1),
	("Dazzling", "Priority moves used by opposing Pokemon targeting this Pokemon or its allies are prevented from having an effect.", 1),
	("Defeatist", "While this Pokemon has 1/2 or less of its maximum HP, its Attack and Special Attack are halved.", 1),
	("Defiant", "This Pokemon''s Attack is raised by 2 stages for each of its stat stages that is lowered by an opposing Pokemon.", 1),
	("Delta Stream", "On switch-in, the weather becomes Delta Stream, which removes the weaknesses of the Flying type from Flying-type Pokemon. This weather remains in effect until this Ability is no longer active for any Pokemon, or the weather is changed by the Desolate Land or Primordial Sea Abilities.", 1),
	("Desolate Land", "On switch-in, the weather becomes Desolate Land, which includes all the effects of Sunny Day and prevents damaging Water-type moves from executing. This weather remains in effect until this Ability is no longer active for any Pokemon, or the weather is changed by the Delta Stream or Primordial Sea Abilities.", 1),
	("Disguise", "If this Pokemon is a Mimikyu, the first hit it takes in battle deals 0 neutral damage. Its disguise is then broken, it changes to Busted Form, and it loses 1/8 of its max HP. Confusion damage also breaks the disguise.", 1),
	("Download", "On switch-in, this Pokemon''s Attack or Special Attack is raised by 1 stage based on the weaker combined defensive stat of all opposing Pokemon. Attack is raised if their Defense is lower, and Special Attack is raised if their Special Defense is the same or lower.", 1),
	("Dragon's Maw", "This Pokemon''s offensive stat is multiplied by 1.5 while using a Dragon-type attack.", 1),
	("Drizzle", "On switch-in, this Pokemon summons Rain Dance.", 1),
	("Drought", "On switch-in, this Pokemon summons Sunny Day.", 1),
	("Dry Skin", "This Pokemon is immune to Water-type moves and restores 1/4 of its maximum HP, rounded down, when hit by a Water-type move. The power of Fire-type moves is multiplied by 1.25 when used on this Pokemon. At the end of each turn, this Pokemon restores 1/8 of its maximum HP, rounded down, if the weather is Rain Dance, and loses 1/8 of its maximum HP, rounded down, if the weather is Sunny Day. The weather effects are prevented if this Pokemon is holding a Utility Umbrella.", 1),
	("Early Bird", "This Pokemon''s sleep counter drops by 2 instead of 1.", 1),
	("Earth Eater", "This Pokemon is immune to Ground-type moves and restores 1/4 of its maximum HP, rounded down, when hit by a Ground-type move.", 1),
	("Effect Spore", "30% chance a Pokemon making contact with this Pokemon will be poisoned, paralyzed, or fall asleep.", 1),
	("Electric Surge", "On switch-in, this Pokemon summons Electric Terrain.", 1),
	("Electromorphosis", "This Pokemon gains the Charge effect when it takes a hit from an attack.", 1),
	("Embody Aspect (Cornerstone)", "On switch-in, this Pokemon''s Defense is raised by 1 stage.", 1),
	("Embody Aspect (Hearthflame)", "On switch-in, this Pokemon''s Attack is raised by 1 stage.", 1),
	("Embody Aspect (Teal)", "On switch-in, this Pokemon''s Speed is raised by 1 stage.", 1),
	("Embody Aspect (Wellspring)", "On switch-in, this Pokemon''s Special Defense is raised by 1 stage.", 1),
	("Emergency Exit", "When this Pokemon has more than 1/2 its maximum HP and takes damage bringing it to 1/2 or less of its maximum HP, it immediately switches out to a chosen ally. This effect applies after all hits from a multi-hit move. This effect is prevented if the move had a secondary effect removed by the Sheer Force Ability. This effect applies to both direct and indirect damage, except Curse and Substitute on use, Belly Drum, Pain Split, and confusion damage.", 1),
	("Fairy Aura", "While this Pokemon is active, the power of Fairy-type moves used by active Pokemon is multiplied by 1.33.", 1),
	("Filter", "This Pokemon receives 3/4 damage from supereffective attacks.", 1),
	("Flame Body", "30% chance a Pokemon making contact with this Pokemon will be burned.", 1),
	("Flare Boost", "While this Pokemon is burned, the power of its special attacks is multiplied by 1.5.", 1),
	("Flash Fire", "This Pokemon is immune to Fire-type moves. The first time it is hit by a Fire-type move, its offensive stat is multiplied by 1.5 while using a Fire-type attack as long as it remains active and has this Ability. If this Pokemon is frozen, it cannot be defrosted by Fire-type attacks.", 1),
	("Flower Gift", "If this Pokemon is a Cherrim and Sunny Day is active, it changes to Sunshine Form and the Attack and Special Defense of it and its allies are multiplied by 1.5. These effects are prevented if the Pokemon is holding a Utility Umbrella.", 1),
	("Flower Veil", "Grass-type Pokemon on this Pokemon''s side cannot have their stat stages lowered by other Pokemon or have a non-volatile status condition inflicted on them by other Pokemon.", 1),
	("Fluffy", "This Pokemon receives 1/2 damage from contact moves, but double damage from Fire moves.", 1),
	("Forecast", "If this Pokemon is a Castform, its type changes to the current weather condition''s type, except Sandstorm. This effect is prevented if this Pokemon is holding a Utility Umbrella and the weather is Rain Dance or Sunny Day.", 1),
	("Forewarn", "On switch-in, this Pokemon is alerted to the move with the highest power, at random, known by an opposing Pokemon. This effect considers OHKO moves to have 150 power, Counter, Mirror Coat, and Metal Burst to have 120 power, every other attacking move with an unspecified power to have 80 power, and non-damaging moves to have 1 power.", 1),
	("Friend Guard", "This Pokemon''s allies receive 3/4 damage from other Pokemo'n's attacks.", 1),
	("Frisk", "On switch-in, this Pokemon identifies the held items of all opposing Pokemon.", 1),
	("Full Metal Body", "Prevents other Pokemon from lowering this Pokemon''s stat stages.", 1),
	("Fur Coat", "This Pokemon''s Defense is doubled.", 1),
	("Gale Wings", "If this Pokemon is at full HP, its Flying-type moves have their priority increased by 1.", 1),
	("Galvanize", "This Pokemon''s Normal-type moves become Electric-type moves and have their power multiplied by 1.2. This effect comes after other effects that change a mov'e's type, but before Ion Deluge and Electri'fy's effects.", 1),
	("Gluttony", "When this Pokemon is holding a Berry that usually activates with 1/4 or less of its maximum HP, it is eaten at 1/2 or less of its maximum HP instead.", 1),
	("Good as Gold", "This Pokemon is immune to Status moves.", 1),
	("Gooey", "Pokemon making contact with this Pokemon have their Speed lowered by 1 stage.", 1),
	("Gorilla Tactics", "This Pokemon''s Attack is multiplied by 1.5, but it can only select the first move it executes. These effects are prevented while this Pokemon is Dynamaxed.", 1),
	("Grass Pelt", "If Grassy Terrain is active, this Pokemon''s Defense is multiplied by 1.5.", 1),
	("Grassy Surge", "On switch-in, this Pokemon summons Grassy Terrain.", 1),
	("Grim Neigh", "This Pokemon''s Special Attack is raised by 1 stage if it attacks and knocks out another Pokemon.", 1),
	("Guard Dog", "This Pokemon is immune to the effect of the Intimidate Ability and raises its Attack by 1 stage instead. This Pokemon cannot be forced to switch out by another Pokemon''s attack or item.", 1),
	("Gulp Missile", "If this Pokemon is a Cramorant, it changes forme when it hits a target with Surf or uses the first turn of Dive successfully. It becomes Gulping Form with an Arrokuda in its mouth if it has more than 1/2 of its maximum HP remaining, or Gorging Form with a Pikachu in its mouth if it has 1/2 or less of its maximum HP remaining. If Cramorant gets hit in Gulping or Gorging Form, it spits the Arrokuda or Pikachu at its attacker, even if it has no HP remaining. The projectile deals damage equal to 1/4 of the target''s maximum HP, rounded down; this damage is blocked by the Magic Guard Ability but not by a substitute. An Arrokuda also lowers the targe't's Defense by 1 stage, and a Pikachu paralyzes the target. Cramorant will return to normal if it spits out a projectile, switches out, or Dynamaxes.", 1),
	("Guts", "If this Pokemon has a non-volatile status condition, its Attack is multiplied by 1.5. This Pokemon''s physical attacks ignore the burn effect of halving damage.", 1),
	("Hadron Engine", "On switch-in, summons Electric Terrain. During Electric Terrain, Sp. Atk is 1.3333x.", 1),
	("Harvest", "If the last item this Pokemon used is a Berry, there is a 50% chance it gets restored at the end of each turn. If Sunny Day is active, this chance is 100%.", 1),
	("Healer", "30% chance this Pokemon''s ally has its non-volatile status condition cured at the end of each turn.", 1),
	("Heatproof", "If a Pokemon uses a Fire-type attack against this Pokemon, that Pokemon''s offensive stat is halved when calculating the damage to this Pokemon. This Pokemon takes half of the usual burn damage, rounded down.", 1),
	("Heavy Metal", "This Pokemon''s weight is doubled. This effect is calculated after the effect of Autotomize, and before the effect of Float Stone.", 1),
	("Honey Gather", "No competitive use.", 1),
	("Hospitality", "On switch-in, this Pokemon restores 1/4 of its ally''s maximum HP, rounded down.", 1),
	("Huge Power", "This Pokemon''s Attack is doubled.", 1),
	("Hunger Switch", "If this Pokemon is a Morpeko, it changes formes between its Full Belly Mode and Hangry Mode at the end of each turn.", 1),
	("Hustle", "This Pokemon''s Attack is multiplied by 1.5 and the accuracy of its physical attacks is multiplied by 0.8.", 1),
	("Hydration", "This Pokemon has its non-volatile status condition cured at the end of each turn if Rain Dance is active. This effect is prevented if this Pokemon is holding a Utility Umbrella.", 1),
	("Hyper Cutter", "Prevents other Pokemon from lowering this Pokemon''s Attack stat stage.", 1),
	("Ice Body", "If Snow is active, this Pokemon restores 1/16 of its maximum HP, rounded down, at the end of each turn.", 1),
	("Ice Face", "If this Pokemon is an Eiscue, the first physical hit it takes in battle deals 0 neutral damage. Its ice face is then broken and it changes forme to Noice Face. Eiscue regains its Ice Face forme when Snow begins or when Eiscue switches in while Snow is active. Confusion damage also breaks the ice face.", 1),
	("Ice Scales", "This Pokemon receives 1/2 damage from special attacks.", 1),
	("Illuminate", "Prevents other Pokemon from lowering this Pokemon''s accuracy stat stage. This Pokemon ignores a targe't's evasiveness stat stage.", 1),
	("Illusion", "When this Pokemon switches in, it appears as the last unfainted Pokemon in its party until it takes direct damage from another Pokemon''s attack. This Pokemo'n's actual level and HP are displayed instead of those of the mimicked Pokemon.", 1),
	("Immunity", "This Pokemon cannot be poisoned. Gaining this Ability while poisoned cures it.", 1),
	("Imposter", "On switch-in, this Pokemon Transforms into the opposing Pokemon that is facing it. If there is no Pokemon at that position, this Pokemon does not Transform.", 1),
	("Infiltrator", "This Pokemon''s moves ignore substitutes and the opposing sid'e's Reflect, Light Screen, Safeguard, Mist, and Aurora Veil.", 1),
	("Innards Out", "If this Pokemon is knocked out with a move, that move''s user loses HP equal to the amount of damage inflicted on this Pokemon.", 1),
	("Inner Focus", "This Pokemon cannot be made to flinch. This Pokemon is immune to the effect of the Intimidate Ability.", 1),
	("Insomnia", "This Pokemon cannot fall asleep. Gaining this Ability while asleep cures it.", 1),
	("Intimidate", "On switch-in, this Pokemon lowers the Attack of opposing Pokemon by 1 stage. Pokemon with the Inner Focus, Oblivious, Own Tempo, or Scrappy Abilities and Pokemon behind a substitute are immune.", 1),
	("Intrepid Sword", "On switch-in, this Pokemon''s Attack is raised by 1 stage. Once per battle.", 1),
	("Iron Barbs", "Pokemon making contact with this Pokemon lose 1/8 of their maximum HP, rounded down.", 1),
	("Iron Fist", "This Pokemon''s punch-based attacks have their power multiplied by 1.2.", 1),
	("Justified", "This Pokemon''s Attack is raised by 1 stage after it is damaged by a Dark-type move.", 1),
	("Keen Eye", "Prevents other Pokemon from lowering this Pokemon''s accuracy stat stage. This Pokemon ignores a targe't's evasiveness stat stage.", 1),
	("Klutz", "This Pokemon''s held item has no effect. This Pokemon cannot use Fling successfully. Macho Brace, Power Anklet, Power Band, Power Belt, Power Bracer, Power Lens, and Power Weight still have their effects.", 1),
	("Leaf Guard", "If Sunny Day is active, this Pokemon cannot become affected by a non-volatile status condition or Yawn, and Rest will fail for it. This effect is prevented if this Pokemon is holding a Utility Umbrella.", 1),
	("Levitate", "This Pokemon is immune to Ground-type attacks and the effects of Spikes, Toxic Spikes, Sticky Web, and the Arena Trap Ability. The effects of Gravity, Ingrain, Smack Down, Thousand Arrows, and Iron Ball nullify the immunity. Thousand Arrows can hit this Pokemon as if it did not have this Ability.", 1),
	("Libero", "This Pokemon''s type changes to match the type of the move it is about to use. This effect comes after all effects that change a mov'e's type. This effect can only happen once per switch-in, and only if this Pokemon is not Terastallized.", 1),
	("Light Metal", "This Pokemon''s weight is halved, rounded down to a tenth of a kilogram. This effect is calculated after the effect of Autotomize, and before the effect of Float Stone. A Pokemo'n's weight will not drop below 0.1 kg.", 1),
	("Lightning Rod", "This Pokemon is immune to Electric-type moves and raises its Special Attack by 1 stage when hit by an Electric-type move. If this Pokemon is not the target of a single-target Electric-type move used by another Pokemon, this Pokemon redirects that move to itself if it is within the range of that move. If multiple Pokemon could redirect with this Ability, it goes to the one with the highest Speed, or in the case of a tie to the one that has had this Ability active longer.", 1),
	("Limber", "This Pokemon cannot be paralyzed. Gaining this Ability while paralyzed cures it.", 1),
	("Lingering Aroma", "Pokemon making contact with this Pokemon have their Ability changed to Lingering Aroma. Does not affect Pokemon with the As One, Battle Bond, Comatose, Commander, Disguise, Gulp Missile, Hadron Engine, Ice Face, Lingering Aroma, Multitype, Orichalcum Pulse, Power Construct, Protosynthesis, Quark Drive, RKS System, Schooling, Shields Down, Stance Change, Zen Mode, or Zero to Hero Abilities.", 1),
	("Liquid Ooze", "This Pokemon damages those draining HP from it for as much as they would heal.", 1),
	("Liquid Voice", "This Pokemon''s sound-based moves become Water-type moves. This effect comes after other effects that change a mov'e's type, but before Ion Deluge and Electri'fy's effects.", 1),
	("Long Reach", "This Pokemon''s attacks do not make contact with the target.", 1),
	("Magic Bounce", "This Pokemon is unaffected by certain non-damaging moves directed at it and will instead use such moves against the original user. Moves reflected in this way are unable to be reflected again by this or Magic Coat''s effect. Spikes, Stealth Rock, Sticky Web, and Toxic Spikes can only be reflected once per side, by the leftmost Pokemon under this or Magic Coa't's effect. The Lightning Rod and Storm Drain Abilities redirect their respective moves before this Ability takes effect.", 1),
	("Magic Guard", "This Pokemon can only be damaged by direct attacks. Curse and Substitute on use, Belly Drum, Pain Split, Struggle recoil, and confusion damage are considered direct damage.", 1),
	("Magician", "If this Pokemon has no item, it steals the item off a Pokemon it hits with an attack. Does not affect Doom Desire and Future Sight.", 1),
	("Magma Armor", "This Pokemon cannot be frozen. Gaining this Ability while frozen cures it.", 1),
	("Magnet Pull", "Prevents opposing Steel-type Pokemon from choosing to switch out, unless they are holding a Shed Shell or are a Ghost type.", 1),
	("Marvel Scale", "If this Pokemon has a non-volatile status condition, its Defense is multiplied by 1.5.", 1),
	("Mega Launcher", "This Pokemon''s pulse moves have their power multiplied by 1.5. Heal Pulse restores 3/4 of a targe't's maximum HP, rounded half down.", 1),
	("Merciless", "This Pokemon''s attacks are critical hits if the target is poisoned.", 1),
	("Mimicry", "This Pokemon''s types change to match the active Terrain when this Pokemon acquires this Ability, or whenever a Terrain begins. Electric type during Electric Terrain, Grass type during Grassy Terrain, Fairy type during Misty Terrain, and Psychic type during Psychic Terrain. If this Ability is acquired without an active Terrain, or a Terrain ends, this Pokemo'n's types become the original types for its species.", 1),
	("Mind's Eye", "This Pokemon can hit Ghost types with Normal- and Fighting-type moves. Prevents other Pokemon from lowering this Pokemon''s accuracy stat stage. This Pokemon ignores a targe't's evasiveness stat stage.", 1),
	("Minus", "If an active ally has this Ability or the Plus Ability, this Pokemon''s Special Attack is multiplied by 1.5.", 1),
	("Mirror Armor", "When one of this Pokemon''s stat stages would be lowered by another Pokemon, that Pokemo'n's stat stage is lowered instead. This effect does not happen if this Pokem'on's stat stage was already -6. If the other Pokemon has a substitute, neither Pokemon has its stat stage lowered.", 1),
	("Misty Surge", "On switch-in, this Pokemon summons Misty Terrain.", 1),
	("Mold Breaker", "This Pokemon''s moves and their effects ignore certain Abilities of other Pokemon. The Abilities that can be negated are Aroma Veil, Aura Break, Battle Armor, Big Pecks, Bulletproof, Clear Body, Contrary, Damp, Dazzling, Disguise, Dry Skin, Filter, Flash Fire, Flower Gift, Flower Veil, Fluffy, Friend Guard, Fur Coat, Grass Pelt, Heatproof, Heavy Metal, Hyper Cutter, Ice Face, Ice Scales, Immunity, Inner Focus, Insomnia, Keen Eye, Leaf Guard, Levitate, Light Metal, Lightning Rod, Limber, Magic Bounce, Magma Armor, Marvel Scale, Mirror Armor, Motor Drive, Multiscale, Oblivious, Overcoat, Own Tempo, Pastel Veil, Punk Rock, Queenly Majesty, Sand Veil, Sap Sipper, Shell Armor, Shield Dust, Simple, Snow Cloak, Solid Rock, Soundproof, Sticky Hold, Storm Drain, Sturdy, Suction Cups, Sweet Veil, Tangled Feet, Telepathy, Thick Fat, Unaware, Vital Spirit, Volt Absorb, Water Absorb, Water Bubble, Water Veil, White Smoke, Wonder Guard, and Wonder Skin. This affects every other Pokemon on the field, whether or not it is a target of this Pokemo'n's move, and whether or not their Ability is beneficial to this Pokemon.", 1),
	("Moody", "This Pokemon has a random stat, other than accuracy or evasiveness, raised by 2 stages and another stat lowered by 1 stage at the end of each turn.", 1),
	("Motor Drive", "This Pokemon is immune to Electric-type moves and raises its Speed by 1 stage when hit by an Electric-type move.", 1),
	("Moxie", "This Pokemon''s Attack is raised by 1 stage if it attacks and knocks out another Pokemon.", 1),
	("Multiscale", "If this Pokemon is at full HP, damage taken from attacks is halved.", 1),
	("Multitype", "If this Pokemon is an Arceus, its type changes to match its held Plate.", 1),
	("Mummy", "Pokemon making contact with this Pokemon have their Ability changed to Mummy. Does not affect Pokemon with the As One, Battle Bond, Comatose, Commander, Disguise, Gulp Missile, Hadron Engine, Ice Face, Multitype, Mummy, Orichalcum Pulse, Power Construct, Protosynthesis, Quark Drive, RKS System, Schooling, Shields Down, Stance Change, Zen Mode, or Zero to Hero Abilities.", 1),
	("Mycelium Might", "This Pokemon''s Status moves ignore certain Abilities of other Pokemon, and go last among Pokemon using the same or greater priority moves.", 1),
	("Natural Cure", "This Pokemon has its non-volatile status condition cured when it switches out.", 1),
	("Neuroforce", "This Pokemon''s attacks that are super effective against the target have their damage multiplied by 1.25.", 1),
	("Neutralizing Gas", "While this Pokemon is active, Abilities have no effect. This Ability activates before hazards and other Abilities take effect. Does not affect the As One, Battle Bond, Comatose, Disguise, Gulp Missile, Ice Face, Multitype, Power Construct, Protosynthesis, Quark Drive, RKS System, Schooling, Shields Down, Stance Change, Zen Mode or Zero to Hero Abilities.", 1),
	("No Guard", "Every move used by or against this Pokemon will always hit.", 1),
	("Normalize", "This Pokemon''s moves are changed to be Normal type and have their power multiplied by 1.2. This effect comes before other effects that change a mov'e's type.", 1),
	("Oblivious", "This Pokemon cannot be infatuated or taunted. Gaining this Ability while infatuated or taunted cures it. This Pokemon is immune to the effect of the Intimidate Ability.", 1),
	("Opportunist", "When an opposing Pokemon has a stat stage raised, this Pokemon copies the effect.", 1),
	("Orichalcum Pulse", "On switch-in, summons Sunny Day. During Sunny Day, Attack is 1.3333x.", 1),
	("Overcoat", "This Pokemon is immune to powder moves, damage from Sandstorm, and the effects of Rage Powder and the Effect Spore Ability.", 1),
	("Overgrow", "When this Pokemon has 1/3 or less of its maximum HP, rounded down, its offensive stat is multiplied by 1.5 while using a Grass-type attack.", 1),
	("Own Tempo", "This Pokemon cannot be confused. Gaining this Ability while confused cures it. This Pokemon is immune to the effect of the Intimidate Ability.", 1),
	("Parental Bond", "This Pokemon''s damaging moves become multi-hit moves that hit twice. The second hit has its damage quartered. Does not affect Doom Desire, Dragon Darts, Dynamax Cannon, Endeavor, Explosion, Final Gambit, Fling, Future Sight, Ice Ball, Rollout, Self-Destruct, any multi-hit move, any move that has multiple targets, or any two-turn move.", 1),
	("Pastel Veil", "This Pokemon and its allies cannot be poisoned. Gaining this Ability while this Pokemon or its ally is poisoned cures them. If this Ability is being ignored during an effect that causes poison, this Pokemon is cured immediately but its ally is not.", 1),
	("Perish Body", "Making contact with this Pokemon starts the Perish Song effect for it and the attacker. This effect does not happen for this Pokemon if the attacker already has a perish count.", 1),
	("Pickpocket", "If this Pokemon has no item and is hit by a contact move, it steals the attacker''s item. This effect applies after all hits from a multi-hit move. This effect is prevented if the move had a secondary effect removed by the Sheer Force Ability.", 1),
	("Pickup", "If this Pokemon has no item, it finds one used by an adjacent Pokemon this turn.", 1),
	("Pixilate", "This Pokemon''s Normal-type moves become Fairy-type moves and have their power multiplied by 1.2. This effect comes after other effects that change a mov'e's type, but before Ion Deluge and Electri'fy's effects.", 1),
	("Plus", "If an active ally has this Ability or the Minus Ability, this Pokemon''s Special Attack is multiplied by 1.5.", 1),
	("Poison Heal", "If this Pokemon is poisoned, it restores 1/8 of its maximum HP, rounded down, at the end of each turn instead of losing HP.", 1),
	("Poison Point", "30% chance a Pokemon making contact with this Pokemon will be poisoned.", 1),
	("Poison Touch", "This Pokemon''s contact moves have a 30% chance of poisoning. This effect comes after a mov'e's inherent secondary effect chance.", 1),
	("Power Construct", "If this Pokemon is a Zygarde in its 10% or 50% Forme, it changes to Complete Forme when it has 1/2 or less of its maximum HP at the end of the turn.", 1),
	("Power of Alchemy", "This Pokemon copies the Ability of an ally that faints. Abilities that cannot be copied are As One, Battle Bond, Comatose, Commander, Disguise, Flower Gift, Forecast, Gulp Missile, Hadron Engine, Hunger Switch, Ice Face, Illusion, Imposter, Multitype, Neutralizing Gas, Orichalcum Pulse, Power Construct, Power of Alchemy, Protosynthesis, Quark Drive, Receiver, RKS System, Schooling, Shields Down, Stance Change, Trace, Wonder Guard, Zen Mode, and Zero to Hero.", 1),
	("Power Spot", "This Pokemon''s allies have the power of their moves multiplied by 1.3. This affects Doom Desire and Future Sight, even if the user is not on the field.", 1),
	("Prankster", "This Pokemon''s non-damaging moves have their priority increased by 1. Opposing Dark-type Pokemon are immune to these moves, and any move called by these moves, if the resulting user of the move has this Ability.", 1),
	("Pressure", "If this Pokemon is the target of an opposing Pokemon''s move, that move loses one additional PP. Imprison, Snatch, and Tera Blast also lose one additional PP when used by an opposing Pokemon, but Sticky Web does not.", 1),
	("Primordial Sea", "On switch-in, the weather becomes Primordial Sea, which includes all the effects of Rain Dance and prevents damaging Fire-type moves from executing. This weather remains in effect until this Ability is no longer active for any Pokemon, or the weather is changed by the Delta Stream or Desolate Land Abilities.", 1),
	("Prism Armor", "This Pokemon receives 3/4 damage from supereffective attacks.", 1),
	("Propeller Tail", "This Pokemon''s moves cannot be redirected to a different target by any effect.", 1),
	("Protean", "This Pokemon''s type changes to match the type of the move it is about to use. This effect comes after all effects that change a mov'e's type. This effect can only happen once per switch-in, and only if this Pokemon is not Terastallized.", 1),
	("Protosynthesis", "If Sunny Day is active or this Pokemon uses a held Booster Energy, this Pokemon''s highest stat is multiplied by 1.3, or by 1.5 if the highest stat is Speed. Stat stage changes are considered at the time this Ability activates. If multiple stats are tied, Attack, Defense, Special Attack, Special Defense, and Speed are prioritized in that order. If this effect was started by Sunny Day, a held Booster Energy will not activate and the effect ends when Sunny Day is no longer active. If this effect was started by a held Booster Energy, it ends when this Pokemon is no longer active.", 1),
	("Psychic Surge", "On switch-in, this Pokemon summons Psychic Terrain.", 1),
	("Punk Rock", "This Pokemon''s sound-based moves have their power multiplied by 1.3. This Pokemon takes halved damage from sound-based moves.", 1),
	("Pure Power", "This Pokemon''s Attack is doubled.", 1),
	("Purifying Salt", "This Pokemon cannot become affected by a non-volatile status condition or Yawn. If a Pokemon uses a Ghost-type attack against this Pokemon, that Pokemon''s offensive stat is halved when calculating the damage to this Pokemon.", 1),
	("Quark Drive", "If Electric Terrain is active or this Pokemon uses a held Booster Energy, this Pokemon''s highest stat is multiplied by 1.3, or by 1.5 if the highest stat is Speed. Stat stage changes are considered at the time this Ability activates. If multiple stats are tied, Attack, Defense, Special Attack, Special Defense, and Speed are prioritized in that order. If this effect was started by Electric Terrain, a held Booster Energy will not activate and the effect ends when Electric Terrain is no longer active. If this effect was started by a held Booster Energy, it ends when this Pokemon is no longer active.", 1),
	("Queenly Majesty", "Priority moves used by opposing Pokemon targeting this Pokemon or its allies are prevented from having an effect.", 1),
	("Quick Draw", "This Pokemon has a 30% chance to move first in its priority bracket with attacking moves.", 1),
	("Quick Feet", "If this Pokemon has a non-volatile status condition, its Speed is multiplied by 1.5. This Pokemon ignores the paralysis effect of halving Speed.", 1),
	("Rain Dish", "If Rain Dance is active, this Pokemon restores 1/16 of its maximum HP, rounded down, at the end of each turn. This effect is prevented if this Pokemon is holding a Utility Umbrella.", 1),
	("Rattled", "This Pokemon''s Speed is raised by 1 stage if hit by a Bug-, Dark-, or Ghost-type attack, or if an opposing Pokemon affected this Pokemon with the Intimidate Ability.", 1),
	("Receiver", "This Pokemon copies the Ability of an ally that faints. Abilities that cannot be copied are As One, Battle Bond, Comatose, Commander, Disguise, Flower Gift, Forecast, Gulp Missile, Hadron Engine, Hunger Switch, Ice Face, Illusion, Imposter, Multitype, Neutralizing Gas, Orichalcum Pulse, Power Construct, Power of Alchemy, Protosynthesis, Quark Drive, Receiver, RKS System, Schooling, Shields Down, Stance Change, Trace, Wonder Guard, Zen Mode, and Zero to Hero.", 1),
	("Reckless", "This Pokemon''s attacks with recoil or crash damage have their power multiplied by 1.2. Does not affect Struggle.", 1),
	("Refrigerate", "This Pokemon''s Normal-type moves become Ice-type moves and have their power multiplied by 1.2. This effect comes after other effects that change a mov'e's type, but before Ion Deluge and Electri'fy's effects.", 1),
	("Regenerator", "This Pokemon restores 1/3 of its maximum HP, rounded down, when it switches out.", 1),
	("Ripen", "When this Pokemon eats certain Berries, the effects are doubled. Berries that restore HP or PP have the amount doubled, Berries that raise stat stages have the amount doubled, Berries that halve damage taken quarter it instead, and a Jaboca Berry or Rowap Berry has the attacker lose 1/4 of its maximum HP, rounded down.", 1),
	("Rivalry", "This Pokemon''s attacks have their power multiplied by 1.25 against targets of the same gender or multiplied by 0.75 against targets of the opposite gender. There is no modifier if either this Pokemon or the target is genderless.", 1),
	("RKS System", "If this Pokemon is a Silvally, its type changes to match its held Memory.", 1),
	("Rock Head", "This Pokemon does not take recoil damage, except Struggle. Does not affect Life Orb damage or crash damage.", 1),
	("Rocky Payload", "This Pokemon''s offensive stat is multiplied by 1.5 while using a Rock-type attack.", 1),
	("Rough Skin", "Pokemon making contact with this Pokemon lose 1/8 of their maximum HP, rounded down.", 1),
	("Run Away", "No competitive use.", 1),
	("Sand Force", "If Sandstorm is active, this Pokemon''s Ground-, Rock-, and Steel-type attacks have their power multiplied by 1.3. This Pokemon takes no damage from Sandstorm.", 1),
	("Sand Rush", "If Sandstorm is active, this Pokemon''s Speed is doubled. This Pokemon takes no damage from Sandstorm.", 1),
	("Sand Spit", "When this Pokemon is hit by an attack, the effect of Sandstorm begins.", 1),
	("Sand Stream", "On switch-in, this Pokemon summons Sandstorm.", 1),
	("Sand Veil", "If Sandstorm is active, the accuracy of moves used against this Pokemon is multiplied by 0.8. This Pokemon takes no damage from Sandstorm.", 1),
	("Sap Sipper", "This Pokemon is immune to Grass-type moves and raises its Attack by 1 stage when hit by a Grass-type move.", 1),
	("Schooling", "On switch-in, if this Pokemon is a Wishiwashi that is level 20 or above and has more than 1/4 of its maximum HP left, it changes to School Form. If it is in School Form and its HP drops to 1/4 of its maximum HP or less, it changes to Solo Form at the end of the turn. If it is in Solo Form and its HP is greater than 1/4 its maximum HP at the end of the turn, it changes to School Form.", 1),
	("Scrappy", "This Pokemon can hit Ghost types with Normal- and Fighting-type moves. This Pokemon is immune to the effect of the Intimidate Ability.", 1),
	("Screen Cleaner", "On switch-in, the effects of Aurora Veil, Light Screen, and Reflect end for both sides.", 1),
	("Seed Sower", "When this Pokemon is hit by an attack, the effect of Grassy Terrain begins.", 1),
	("Serene Grace", "This Pokemon''s moves have their secondary effect chance doubled. This effect stacks with the Rainbow effect, except for secondary effects that cause the target to flinch.", 1),
	("Shadow Shield", "If this Pokemon is at full HP, damage taken from attacks is halved.", 1),
	("Shadow Tag", "Prevents opposing Pokemon from choosing to switch out, unless they are holding a Shed Shell, are a Ghost type, or also have this Ability.", 1),
	("Sharpness", "This Pokemon''s slicing moves have their power multiplied by 1.5.", 1),
	("Shed Skin", "This Pokemon has a 33% chance to have its non-volatile status condition cured at the end of each turn.", 1),
	("Sheer Force", "This Pokemon''s attacks with secondary effects have their power multiplied by 1.3, but the secondary effects are removed. If a secondary effect was removed, it also removes the use'r's Life Orb recoil and Shell Bell recovery, and prevents the targ'et's Anger Shell, Berserk, Color Change, Emergency Exit, Pickpocket, Wimp Out, Red Card, Eject Button, Kee Berry, and Maranga Berry from activating.", 1),
	("Shell Armor", "This Pokemon cannot be struck by a critical hit.", 1),
	("Shield Dust", "This Pokemon is not affected by the secondary effect of another Pokemon''s attack.", 1),
	("Shields Down", "If this Pokemon is a Minior, it changes to its Core forme if it has 1/2 or less of its maximum HP, and changes to Meteor Form if it has more than 1/2 its maximum HP. This check is done on switch-in and at the end of each turn. While in its Meteor Form, it cannot become affected by a non-volatile status condition or Yawn.", 1),
	("Simple", "When one of this Pokemon''s stat stages is raised or lowered, the amount is doubled.", 1),
	("Skill Link", "This Pokemon''s multi-hit attacks always hit the maximum number of times. Triple Kick and Triple Axel do not check accuracy for the second and third hits.", 1),
	("Slow Start", "On switch-in, this Pokemon''s Attack and Speed are halved for 5 turns.", 1),
	("Slush Rush", "If Snow is active, this Pokemon''s Speed is doubled.", 1),
	("Sniper", "If this Pokemon strikes with a critical hit, the damage is multiplied by 1.5.", 1),
	("Snow Cloak", "If Snow is active, the accuracy of moves used against this Pokemon is multiplied by 0.8.", 1),
	("Snow Warning", "On switch-in, this Pokemon summons Snow.", 1),
	("Solar Power", "If Sunny Day is active, this Pokemon''s Special Attack is multiplied by 1.5 and it loses 1/8 of its maximum HP, rounded down, at the end of each turn. These effects are prevented if the Pokemon is holding a Utility Umbrella.", 1),
	("Solid Rock", "This Pokemon receives 3/4 damage from supereffective attacks.", 1),
	("Soul-Heart", "This Pokemon''s Special Attack is raised by 1 stage when another Pokemon faints.", 1),
	("Soundproof", "This Pokemon is immune to sound-based moves, unless it used the move.", 1),
	("Speed Boost", "This Pokemon''s Speed is raised by 1 stage at the end of each full turn it has been on the field.", 1),
	("Stakeout", "This Pokemon''s offensive stat is doubled against a target that switched in this turn.", 1),
	("Stall", "This Pokemon moves last among Pokemon using the same or greater priority moves.", 1),
	("Stalwart", "This Pokemon''s moves cannot be redirected to a different target by any effect.", 1),
	("Stamina", "This Pokemon''s Defense is raised by 1 stage after it is damaged by a move.", 1),
	("Stance Change", "If this Pokemon is an Aegislash, it changes to Blade Forme before using an attacking move, and changes to Shield Forme before using King''s Shield.", 1),
	("Static", "30% chance a Pokemon making contact with this Pokemon will be paralyzed.", 1),
	("Steadfast", "If this Pokemon flinches, its Speed is raised by 1 stage.", 1),
	("Steam Engine", "This Pokemon''s Speed is raised by 6 stages after it is damaged by a Fire- or Water-type move.", 1),
	("Steelworker", "This Pokemon''s offensive stat is multiplied by 1.5 while using a Steel-type attack.", 1),
	("Steely Spirit", "This Pokemon and its allies'' Steel-type moves have their power multiplied by 1.5. This affects Doom Desire even if the user is not on the field.", 1),
	("Stench", "This Pokemon''s attacks without a chance to make the target flinch gain a 10% chance to make the target flinch.", 1),
	("Sticky Hold", "This Pokemon cannot lose its held item due to another Pokemon''s Ability or attack, unless the attack knocks out this Pokemon. A Sticky Barb will be transferred to other Pokemon regardless of this Ability.", 1),
	("Storm Drain", "This Pokemon is immune to Water-type moves and raises its Special Attack by 1 stage when hit by a Water-type move. If this Pokemon is not the target of a single-target Water-type move used by another Pokemon, this Pokemon redirects that move to itself if it is within the range of that move. If multiple Pokemon could redirect with this Ability, it goes to the one with the highest Speed, or in the case of a tie to the one that has had this Ability active longer.", 1),
	("Strong Jaw", "This Pokemon''s bite-based attacks have their power multiplied by 1.5.", 1),
	("Sturdy", "If this Pokemon is at full HP, it survives one hit with at least 1 HP. OHKO moves fail when used against this Pokemon.", 1),
	("Suction Cups", "This Pokemon cannot be forced to switch out by another Pokemon''s attack or item.", 1),
	("Super Luck", "This Pokemon''s critical hit ratio is raised by 1 stage.", 1),
	("Supersweet Syrup", "On switch-in, this Pokemon lowers the evasiveness of opponents 1 stage. Once per battle.", 1),
	("Supreme Overlord", "This Pokemon''s moves have their power multiplied by 1+(X*0.1), where X is the total number of times any Pokemon has fainted on the use'r's side when this Ability became active, and X cannot be greater than 5.", 1),
	("Surge Surfer", "If Electric Terrain is active, this Pokemon''s Speed is doubled.", 1),
	("Swarm", "When this Pokemon has 1/3 or less of its maximum HP, rounded down, its offensive stat is multiplied by 1.5 while using a Bug-type attack.", 1),
	("Sweet Veil", "This Pokemon and its allies cannot fall asleep, but those already asleep do not wake up immediately. This Pokemon and its allies cannot use Rest successfully or become affected by Yawn, and those previously affected will not fall asleep.", 1),
	("Swift Swim", "If Rain Dance is active, this Pokemon''s Speed is doubled. This effect is prevented if this Pokemon is holding a Utility Umbrella.", 1),
	("Symbiosis", "If an ally uses its item, this Pokemon gives its item to that ally immediately. Does not activate if the ally''s item was stolen or knocked off, or if the ally used an Eject Button or Eject Pack.", 1),
	("Synchronize", "If another Pokemon burns, paralyzes, poisons, or badly poisons this Pokemon, that Pokemon receives the same non-volatile status condition.", 1),
	("Sword of Ruin", "Active Pokemon without this Ability have their Defense multiplied by 0.75.", 1),
	("Tablets of Ruin", "Active Pokemon without this Ability have their Attack multiplied by 0.75.", 1),
	("Tangled Feet", "This Pokemon''s evasiveness is doubled as long as it is confused.", 1),
	("Tangling Hair", "Pokemon making contact with this Pokemon have their Speed lowered by 1 stage.", 1),
	("Technician", "This Pokemon''s moves of 60 power or less have their power multiplied by 1.5, including Struggle. This effect comes after a mov'e's effect changes its own power.", 1),
	("Telepathy", "This Pokemon does not take damage from attacks made by its allies.", 1),
	("Teravolt", "This Pokemon''s moves and their effects ignore certain Abilities of other Pokemon. The Abilities that can be negated are Aroma Veil, Aura Break, Battle Armor, Big Pecks, Bulletproof, Clear Body, Contrary, Damp, Dazzling, Disguise, Dry Skin, Filter, Flash Fire, Flower Gift, Flower Veil, Fluffy, Friend Guard, Fur Coat, Grass Pelt, Heatproof, Heavy Metal, Hyper Cutter, Ice Face, Ice Scales, Immunity, Inner Focus, Insomnia, Keen Eye, Leaf Guard, Levitate, Light Metal, Lightning Rod, Limber, Magic Bounce, Magma Armor, Marvel Scale, Mirror Armor, Motor Drive, Multiscale, Oblivious, Overcoat, Own Tempo, Pastel Veil, Punk Rock, Queenly Majesty, Sand Veil, Sap Sipper, Shell Armor, Shield Dust, Simple, Snow Cloak, Solid Rock, Soundproof, Sticky Hold, Storm Drain, Sturdy, Suction Cups, Sweet Veil, Tangled Feet, Telepathy, Thick Fat, Unaware, Vital Spirit, Volt Absorb, Water Absorb, Water Bubble, Water Veil, White Smoke, Wonder Guard, and Wonder Skin. This affects every other Pokemon on the field, whether or not it is a target of this Pokemo'n's move, and whether or not their Ability is beneficial to this Pokemon.", 1),
	("Thermal Exchange", "This Pokemon''s Attack is raised 1 stage after it is damaged by a Fire-type move. This Pokemon cannot be burned. Gaining this Ability while burned cures it.", 1),
	("Thick Fat", "If a Pokemon uses a Fire- or Ice-type attack against this Pokemon, that Pokemon''s offensive stat is halved when calculating the damage to this Pokemon.", 1),
	("Tinted Lens", "This Pokemon''s attacks that are not very effective on a target deal double damage.", 1),
	("Torrent", "When this Pokemon has 1/3 or less of its maximum HP, rounded down, its offensive stat is multiplied by 1.5 while using a Water-type attack.", 1),
	("Tough Claws", "This Pokemon''s contact moves have their power multiplied by 1.3.", 1),
	("Toxic Boost", "While this Pokemon is poisoned, the power of its physical attacks is multiplied by 1.5.", 1),
	("Toxic Chain", "This Pokemon''s moves have a 30% chance of badly poisoning. This effect comes after a mov'e's inherent secondary effect chance.", 1),
	("Toxic Debris", "If this Pokemon is hit by a physical attack, Toxic Spikes are set on the opposing side.", 1),
	("Trace", "On switch-in, this Pokemon copies a random opposing Pokemon''s Ability. Abilities that cannot be copied are As One, Battle Bond, Comatose, Commander, Disguise, Flower Gift, Forecast, Gulp Missile, Hadron Engine, Hunger Switch, Ice Face, Illusion, Imposter, Multitype, Neutralizing Gas, Orichalcum Pulse, Power Construct, Power of Alchemy, Protosynthesis, Quark Drive, Receiver, RKS System, Schooling, Shields Down, Stance Change, Trace, Zen Mode, and Zero to Hero. If no opposing Pokemon has an Ability that can be copied, this Ability will activate as soon as one does.", 1),
	("Transistor", "This Pokemon''s offensive stat is multiplied by 1.3 while using an Electric-type attack.", 1),
	("Triage", "This Pokemon''s healing moves have their priority increased by 3.", 1),
	("Truant", "This Pokemon skips every other turn instead of using a move.", 1),
	("Turboblaze", "This Pokemon''s moves and their effects ignore certain Abilities of other Pokemon. The Abilities that can be negated are Aroma Veil, Aura Break, Battle Armor, Big Pecks, Bulletproof, Clear Body, Contrary, Damp, Dazzling, Disguise, Dry Skin, Filter, Flash Fire, Flower Gift, Flower Veil, Fluffy, Friend Guard, Fur Coat, Grass Pelt, Heatproof, Heavy Metal, Hyper Cutter, Ice Face, Ice Scales, Immunity, Inner Focus, Insomnia, Keen Eye, Leaf Guard, Levitate, Light Metal, Lightning Rod, Limber, Magic Bounce, Magma Armor, Marvel Scale, Mirror Armor, Motor Drive, Multiscale, Oblivious, Overcoat, Own Tempo, Pastel Veil, Punk Rock, Queenly Majesty, Sand Veil, Sap Sipper, Shell Armor, Shield Dust, Simple, Snow Cloak, Solid Rock, Soundproof, Sticky Hold, Storm Drain, Sturdy, Suction Cups, Sweet Veil, Tangled Feet, Telepathy, Thick Fat, Unaware, Vital Spirit, Volt Absorb, Water Absorb, Water Bubble, Water Veil, White Smoke, Wonder Guard, and Wonder Skin. This affects every other Pokemon on the field, whether or not it is a target of this Pokemo'n's move, and whether or not their Ability is beneficial to this Pokemon.", 1),
	("Unaware", "This Pokemon ignores other Pokemon''s Attack, Special Attack, and accuracy stat stages when taking damage, and ignores other Pokemo'n's Defense, Special Defense, and evasiveness stat stages when dealing damage.", 1),
	("Unburden", "If this Pokemon loses its held item for any reason, its Speed is doubled as long as it remains active, has this Ability, and is not holding an item.", 1),
	("Unnerve", "While this Pokemon is active, it prevents opposing Pokemon from using their Berries. This Ability activates before hazards and other Abilities take effect.", 1),
	("Unseen Fist", "This Pokemon''s contact moves ignore the targe't's protection, except Max Guard.", 1),
	("Vessel of Ruin", "Active Pokemon without this Ability have their Special Attack multiplied by 0.75.", 1),
	("Victory Star", "This Pokemon and its allies'' moves have their accuracy multiplied by 1.1.", 1),
	("Vital Spirit", "This Pokemon cannot fall asleep. Gaining this Ability while asleep cures it.", 1),
	("Volt Absorb", "This Pokemon is immune to Electric-type moves and restores 1/4 of its maximum HP, rounded down, when hit by an Electric-type move.", 1),
	("Wandering Spirit", "Pokemon making contact with this Pokemon have their Ability swapped with this one. Does not affect Pokemon with the As One, Battle Bond, Comatose, Commander, Disguise, Gulp Missile, Hadron Engine, Hunger Switch, Ice Face, Illusion, Multitype, Neutralizing Gas, Orichalcum Pulse, Power Construct, Protosynthesis, Quark Drive, RKS System, Schooling, Shields Down, Stance Change, Wonder Guard, Zen Mode, or Zero to Hero Abilities.", 1),
	("Water Absorb", "This Pokemon is immune to Water-type moves and restores 1/4 of its maximum HP, rounded down, when hit by a Water-type move.", 1),
	("Water Bubble", "This Pokemon''s offensive stat is doubled while using a Water-type attack. If a Pokemon uses a Fire-type attack against this Pokemon, that Pokemo'n's offensive stat is halved when calculating the damage to this Pokemon. This Pokemon cannot be burned. Gaining this Ability while burned cures it.", 1),
	("Water Compaction", "This Pokemon''s Defense is raised 2 stages after it is damaged by a Water-type move.", 1),
	("Water Veil", "This Pokemon cannot be burned. Gaining this Ability while burned cures it.", 1),
	("Weak Armor", "If a physical attack hits this Pokemon, its Defense is lowered by 1 stage and its Speed is raised by 2 stages.", 1),
	("Well-Baked Body", "This Pokemon is immune to Fire-type moves and raises its Defense by 2 stages when hit by a Fire-type move.", 1),
	("White Smoke", "Prevents other Pokemon from lowering this Pokemon''s stat stages.", 1),
	("Wimp Out", "When this Pokemon has more than 1/2 its maximum HP and takes damage bringing it to 1/2 or less of its maximum HP, it immediately switches out to a chosen ally. This effect applies after all hits from a multi-hit move. This effect is prevented if the move had a secondary effect removed by the Sheer Force Ability. This effect applies to both direct and indirect damage, except Curse and Substitute on use, Belly Drum, Pain Split, and confusion damage.", 1),
	("Wind Power", "This Pokemon gains the Charge effect when it takes a hit from a wind move or when Tailwind begins on this Pokemon''s side.", 1),
	("Wind Rider", "This Pokemon is immune to wind moves and raises its Attack by 1 stage when hit by a wind move or when Tailwind begins on this Pokemon''s side.", 1),
	("Wonder Guard", "This Pokemon can only be damaged by supereffective moves and indirect damage.", 1),
	("Wonder Skin", "Non-damaging moves that check accuracy have their accuracy changed to 50% when used against this Pokemon. This effect comes before other effects that modify accuracy.", 1),
	("Zen Mode", "If this Pokemon is a Darmanitan or Galarian Darmanitan, it changes to Zen Mode if it has 1/2 or less of its maximum HP at the end of a turn. If Darmanitan''s HP is above 1/2 of its maximum HP at the end of a turn, it changes back to Standard Mode.", 1),
	("Zero to Hero", "If this Pokemon is a Palafin in Zero Form, switching out has it change to Hero Form.", 1),
	("Mountaineer", "On switch-in, this Pokemon avoids all Rock-type attacks and Stealth Rock.", 1),
	("Rebound", "On switch-in, this Pokemon blocks certain status moves and instead uses the move against the original user.", 1),
	("Persistent", "The duration of Gravity, Heal Block, Magic Room, Safeguard, Tailwind, Trick Room, and Wonder Room is increased by 2 turns if the effect is started by this Pokemon.", 1)
);
